// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/dcutr.proto
// Protobuf C++ Version: 6.33.4

#ifndef proto_2fdcutr_2eproto_2epb_2eh
#define proto_2fdcutr_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_proto_2fdcutr_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fdcutr_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_proto_2fdcutr_2eproto;
}  // extern "C"
namespace p2p {
namespace protocol {
namespace dcutr {
enum DCUtRMessage_Type : int;
extern const uint32_t DCUtRMessage_Type_internal_data_[];
class Connect;
struct ConnectDefaultTypeInternal;
extern ConnectDefaultTypeInternal _Connect_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Connect_class_data_;
class DCUtRMessage;
struct DCUtRMessageDefaultTypeInternal;
extern DCUtRMessageDefaultTypeInternal _DCUtRMessage_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull DCUtRMessage_class_data_;
class Sync;
struct SyncDefaultTypeInternal;
extern SyncDefaultTypeInternal _Sync_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Sync_class_data_;
}  // namespace dcutr
}  // namespace protocol
}  // namespace p2p
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::p2p::protocol::dcutr::DCUtRMessage_Type_internal_data_>
    internal::EnumTraitsImpl::value<::p2p::protocol::dcutr::DCUtRMessage_Type>;
}  // namespace protobuf
}  // namespace google

namespace p2p {
namespace protocol {
namespace dcutr {
enum DCUtRMessage_Type : int {
  DCUtRMessage_Type_CONNECT = 0,
  DCUtRMessage_Type_SYNC = 1,
  DCUtRMessage_Type_DCUtRMessage_Type_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  DCUtRMessage_Type_DCUtRMessage_Type_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t DCUtRMessage_Type_internal_data_[];
inline constexpr DCUtRMessage_Type DCUtRMessage_Type_Type_MIN =
    static_cast<DCUtRMessage_Type>(0);
inline constexpr DCUtRMessage_Type DCUtRMessage_Type_Type_MAX =
    static_cast<DCUtRMessage_Type>(1);
inline bool DCUtRMessage_Type_IsValid(int value) {
  return 0 <= value && value <= 1;
}
inline constexpr int DCUtRMessage_Type_Type_ARRAYSIZE = 1 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL DCUtRMessage_Type_descriptor();
template <typename T>
const ::std::string& DCUtRMessage_Type_Name(T value) {
  static_assert(::std::is_same<T, DCUtRMessage_Type>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Type_Name().");
  return DCUtRMessage_Type_Name(static_cast<DCUtRMessage_Type>(value));
}
template <>
inline const ::std::string& DCUtRMessage_Type_Name(DCUtRMessage_Type value) {
  return ::google::protobuf::internal::NameOfDenseEnum<DCUtRMessage_Type_descriptor, 0, 1>(
      static_cast<int>(value));
}
inline bool DCUtRMessage_Type_Parse(
    ::absl::string_view name, DCUtRMessage_Type* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<DCUtRMessage_Type>(DCUtRMessage_Type_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class Sync final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:p2p.protocol.dcutr.Sync) */ {
 public:
  inline Sync() : Sync(nullptr) {}
  ~Sync() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Sync* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Sync));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Sync(::google::protobuf::internal::ConstantInitialized);

  inline Sync(const Sync& from) : Sync(nullptr, from) {}
  inline Sync(Sync&& from) noexcept
      : Sync(nullptr, ::std::move(from)) {}
  inline Sync& operator=(const Sync& from) {
    CopyFrom(from);
    return *this;
  }
  inline Sync& operator=(Sync&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Sync& default_instance() {
    return *reinterpret_cast<const Sync*>(
        &_Sync_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(Sync& a, Sync& b) { a.Swap(&b); }
  inline void Swap(Sync* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Sync* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Sync* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Sync>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Sync& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Sync& from) { Sync::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Sync* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "p2p.protocol.dcutr.Sync"; }

  explicit Sync(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Sync(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Sync& from);
  Sync(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Sync&& from) noexcept
      : Sync(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAddrsFieldNumber = 1,
    kEchoTimestampNsFieldNumber = 2,
    kTimestampNsFieldNumber = 3,
  };
  // repeated bytes addrs = 1;
  int addrs_size() const;
  private:
  int _internal_addrs_size() const;

  public:
  void clear_addrs() ;
  const ::std::string& addrs(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_addrs(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_addrs(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_addrs();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_addrs(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& addrs() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_addrs();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_addrs() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_addrs();

  public:
  // int64 echo_timestamp_ns = 2;
  void clear_echo_timestamp_ns() ;
  ::int64_t echo_timestamp_ns() const;
  void set_echo_timestamp_ns(::int64_t value);

  private:
  ::int64_t _internal_echo_timestamp_ns() const;
  void _internal_set_echo_timestamp_ns(::int64_t value);

  public:
  // int64 timestamp_ns = 3;
  void clear_timestamp_ns() ;
  ::int64_t timestamp_ns() const;
  void set_timestamp_ns(::int64_t value);

  private:
  ::int64_t _internal_timestamp_ns() const;
  void _internal_set_timestamp_ns(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:p2p.protocol.dcutr.Sync)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Sync& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField<::std::string> addrs_;
    ::int64_t echo_timestamp_ns_;
    ::int64_t timestamp_ns_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fdcutr_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Sync_class_data_;
// -------------------------------------------------------------------

class Connect final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:p2p.protocol.dcutr.Connect) */ {
 public:
  inline Connect() : Connect(nullptr) {}
  ~Connect() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Connect* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Connect));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Connect(::google::protobuf::internal::ConstantInitialized);

  inline Connect(const Connect& from) : Connect(nullptr, from) {}
  inline Connect(Connect&& from) noexcept
      : Connect(nullptr, ::std::move(from)) {}
  inline Connect& operator=(const Connect& from) {
    CopyFrom(from);
    return *this;
  }
  inline Connect& operator=(Connect&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Connect& default_instance() {
    return *reinterpret_cast<const Connect*>(
        &_Connect_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Connect& a, Connect& b) { a.Swap(&b); }
  inline void Swap(Connect* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Connect* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Connect* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Connect>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Connect& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Connect& from) { Connect::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Connect* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "p2p.protocol.dcutr.Connect"; }

  explicit Connect(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Connect(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Connect& from);
  Connect(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Connect&& from) noexcept
      : Connect(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAddrsFieldNumber = 1,
    kTimestampNsFieldNumber = 2,
  };
  // repeated bytes addrs = 1;
  int addrs_size() const;
  private:
  int _internal_addrs_size() const;

  public:
  void clear_addrs() ;
  const ::std::string& addrs(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_addrs(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_addrs(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_addrs();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_addrs(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& addrs() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_addrs();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_addrs() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_addrs();

  public:
  // int64 timestamp_ns = 2;
  void clear_timestamp_ns() ;
  ::int64_t timestamp_ns() const;
  void set_timestamp_ns(::int64_t value);

  private:
  ::int64_t _internal_timestamp_ns() const;
  void _internal_set_timestamp_ns(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:p2p.protocol.dcutr.Connect)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Connect& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField<::std::string> addrs_;
    ::int64_t timestamp_ns_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fdcutr_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Connect_class_data_;
// -------------------------------------------------------------------

class DCUtRMessage final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:p2p.protocol.dcutr.DCUtRMessage) */ {
 public:
  inline DCUtRMessage() : DCUtRMessage(nullptr) {}
  ~DCUtRMessage() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DCUtRMessage* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DCUtRMessage));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DCUtRMessage(::google::protobuf::internal::ConstantInitialized);

  inline DCUtRMessage(const DCUtRMessage& from) : DCUtRMessage(nullptr, from) {}
  inline DCUtRMessage(DCUtRMessage&& from) noexcept
      : DCUtRMessage(nullptr, ::std::move(from)) {}
  inline DCUtRMessage& operator=(const DCUtRMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline DCUtRMessage& operator=(DCUtRMessage&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DCUtRMessage& default_instance() {
    return *reinterpret_cast<const DCUtRMessage*>(
        &_DCUtRMessage_default_instance_);
  }
  enum PayloadCase {
    kConnect = 2,
    kSync = 3,
    PAYLOAD_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(DCUtRMessage& a, DCUtRMessage& b) { a.Swap(&b); }
  inline void Swap(DCUtRMessage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DCUtRMessage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DCUtRMessage* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<DCUtRMessage>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DCUtRMessage& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DCUtRMessage& from) { DCUtRMessage::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(DCUtRMessage* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "p2p.protocol.dcutr.DCUtRMessage"; }

  explicit DCUtRMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  DCUtRMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const DCUtRMessage& from);
  DCUtRMessage(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, DCUtRMessage&& from) noexcept
      : DCUtRMessage(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Type = DCUtRMessage_Type;
  static constexpr Type CONNECT = DCUtRMessage_Type_CONNECT;
  static constexpr Type SYNC = DCUtRMessage_Type_SYNC;
  static inline bool Type_IsValid(int value) {
    return DCUtRMessage_Type_IsValid(value);
  }
  static constexpr Type Type_MIN = DCUtRMessage_Type_Type_MIN;
  static constexpr Type Type_MAX = DCUtRMessage_Type_Type_MAX;
  static constexpr int Type_ARRAYSIZE = DCUtRMessage_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Type_descriptor() {
    return DCUtRMessage_Type_descriptor();
  }
  template <typename T>
  static inline const ::std::string& Type_Name(T value) {
    return DCUtRMessage_Type_Name(value);
  }
  static inline bool Type_Parse(
      ::absl::string_view name, Type* PROTOBUF_NONNULL value) {
    return DCUtRMessage_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kTypeFieldNumber = 1,
    kConnectFieldNumber = 2,
    kSyncFieldNumber = 3,
  };
  // .p2p.protocol.dcutr.DCUtRMessage.Type type = 1;
  void clear_type() ;
  ::p2p::protocol::dcutr::DCUtRMessage_Type type() const;
  void set_type(::p2p::protocol::dcutr::DCUtRMessage_Type value);

  private:
  ::p2p::protocol::dcutr::DCUtRMessage_Type _internal_type() const;
  void _internal_set_type(::p2p::protocol::dcutr::DCUtRMessage_Type value);

  public:
  // .p2p.protocol.dcutr.Connect connect = 2;
  bool has_connect() const;
  private:
  bool _internal_has_connect() const;

  public:
  void clear_connect() ;
  const ::p2p::protocol::dcutr::Connect& connect() const;
  [[nodiscard]] ::p2p::protocol::dcutr::Connect* PROTOBUF_NULLABLE release_connect();
  ::p2p::protocol::dcutr::Connect* PROTOBUF_NONNULL mutable_connect();
  void set_allocated_connect(::p2p::protocol::dcutr::Connect* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_connect(::p2p::protocol::dcutr::Connect* PROTOBUF_NULLABLE value);
  ::p2p::protocol::dcutr::Connect* PROTOBUF_NULLABLE unsafe_arena_release_connect();

  private:
  const ::p2p::protocol::dcutr::Connect& _internal_connect() const;
  ::p2p::protocol::dcutr::Connect* PROTOBUF_NONNULL _internal_mutable_connect();

  public:
  // .p2p.protocol.dcutr.Sync sync = 3;
  bool has_sync() const;
  private:
  bool _internal_has_sync() const;

  public:
  void clear_sync() ;
  const ::p2p::protocol::dcutr::Sync& sync() const;
  [[nodiscard]] ::p2p::protocol::dcutr::Sync* PROTOBUF_NULLABLE release_sync();
  ::p2p::protocol::dcutr::Sync* PROTOBUF_NONNULL mutable_sync();
  void set_allocated_sync(::p2p::protocol::dcutr::Sync* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_sync(::p2p::protocol::dcutr::Sync* PROTOBUF_NULLABLE value);
  ::p2p::protocol::dcutr::Sync* PROTOBUF_NULLABLE unsafe_arena_release_sync();

  private:
  const ::p2p::protocol::dcutr::Sync& _internal_sync() const;
  ::p2p::protocol::dcutr::Sync* PROTOBUF_NONNULL _internal_mutable_sync();

  public:
  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:p2p.protocol.dcutr.DCUtRMessage)
 private:
  class _Internal;
  void set_has_connect();
  void set_has_sync();
  inline bool has_payload() const;
  inline void clear_has_payload();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 3,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const DCUtRMessage& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    int type_;
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::p2p::protocol::dcutr::Connect* PROTOBUF_NULLABLE connect_;
      ::p2p::protocol::dcutr::Sync* PROTOBUF_NULLABLE sync_;
    } payload_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fdcutr_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull DCUtRMessage_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// DCUtRMessage

// .p2p.protocol.dcutr.DCUtRMessage.Type type = 1;
inline void DCUtRMessage::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::p2p::protocol::dcutr::DCUtRMessage_Type DCUtRMessage::type() const {
  // @@protoc_insertion_point(field_get:p2p.protocol.dcutr.DCUtRMessage.type)
  return _internal_type();
}
inline void DCUtRMessage::set_type(::p2p::protocol::dcutr::DCUtRMessage_Type value) {
  _internal_set_type(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:p2p.protocol.dcutr.DCUtRMessage.type)
}
inline ::p2p::protocol::dcutr::DCUtRMessage_Type DCUtRMessage::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::p2p::protocol::dcutr::DCUtRMessage_Type>(_impl_.type_);
}
inline void DCUtRMessage::_internal_set_type(::p2p::protocol::dcutr::DCUtRMessage_Type value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// .p2p.protocol.dcutr.Connect connect = 2;
inline bool DCUtRMessage::has_connect() const {
  return payload_case() == kConnect;
}
inline bool DCUtRMessage::_internal_has_connect() const {
  return payload_case() == kConnect;
}
inline void DCUtRMessage::set_has_connect() {
  _impl_._oneof_case_[0] = kConnect;
}
inline void DCUtRMessage::clear_connect() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kConnect) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.connect_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.connect_);
    }
    clear_has_payload();
  }
}
inline ::p2p::protocol::dcutr::Connect* PROTOBUF_NULLABLE DCUtRMessage::release_connect() {
  // @@protoc_insertion_point(field_release:p2p.protocol.dcutr.DCUtRMessage.connect)
  if (payload_case() == kConnect) {
    clear_has_payload();
    auto* temp = _impl_.payload_.connect_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.connect_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::p2p::protocol::dcutr::Connect& DCUtRMessage::_internal_connect() const {
  return payload_case() == kConnect ? static_cast<const ::p2p::protocol::dcutr::Connect&>(*_impl_.payload_.connect_)
                     : reinterpret_cast<const ::p2p::protocol::dcutr::Connect&>(::p2p::protocol::dcutr::_Connect_default_instance_);
}
inline const ::p2p::protocol::dcutr::Connect& DCUtRMessage::connect() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:p2p.protocol.dcutr.DCUtRMessage.connect)
  return _internal_connect();
}
inline ::p2p::protocol::dcutr::Connect* PROTOBUF_NULLABLE DCUtRMessage::unsafe_arena_release_connect() {
  // @@protoc_insertion_point(field_unsafe_arena_release:p2p.protocol.dcutr.DCUtRMessage.connect)
  if (payload_case() == kConnect) {
    clear_has_payload();
    auto* temp = _impl_.payload_.connect_;
    _impl_.payload_.connect_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void DCUtRMessage::unsafe_arena_set_allocated_connect(
    ::p2p::protocol::dcutr::Connect* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_connect();
    _impl_.payload_.connect_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:p2p.protocol.dcutr.DCUtRMessage.connect)
}
inline ::p2p::protocol::dcutr::Connect* PROTOBUF_NONNULL DCUtRMessage::_internal_mutable_connect() {
  if (payload_case() != kConnect) {
    clear_payload();
    set_has_connect();
    _impl_.payload_.connect_ = 
        ::google::protobuf::Message::DefaultConstruct<::p2p::protocol::dcutr::Connect>(GetArena());
  }
  return _impl_.payload_.connect_;
}
inline ::p2p::protocol::dcutr::Connect* PROTOBUF_NONNULL DCUtRMessage::mutable_connect()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::p2p::protocol::dcutr::Connect* _msg = _internal_mutable_connect();
  // @@protoc_insertion_point(field_mutable:p2p.protocol.dcutr.DCUtRMessage.connect)
  return _msg;
}

// .p2p.protocol.dcutr.Sync sync = 3;
inline bool DCUtRMessage::has_sync() const {
  return payload_case() == kSync;
}
inline bool DCUtRMessage::_internal_has_sync() const {
  return payload_case() == kSync;
}
inline void DCUtRMessage::set_has_sync() {
  _impl_._oneof_case_[0] = kSync;
}
inline void DCUtRMessage::clear_sync() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kSync) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.sync_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.sync_);
    }
    clear_has_payload();
  }
}
inline ::p2p::protocol::dcutr::Sync* PROTOBUF_NULLABLE DCUtRMessage::release_sync() {
  // @@protoc_insertion_point(field_release:p2p.protocol.dcutr.DCUtRMessage.sync)
  if (payload_case() == kSync) {
    clear_has_payload();
    auto* temp = _impl_.payload_.sync_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.sync_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::p2p::protocol::dcutr::Sync& DCUtRMessage::_internal_sync() const {
  return payload_case() == kSync ? static_cast<const ::p2p::protocol::dcutr::Sync&>(*_impl_.payload_.sync_)
                     : reinterpret_cast<const ::p2p::protocol::dcutr::Sync&>(::p2p::protocol::dcutr::_Sync_default_instance_);
}
inline const ::p2p::protocol::dcutr::Sync& DCUtRMessage::sync() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:p2p.protocol.dcutr.DCUtRMessage.sync)
  return _internal_sync();
}
inline ::p2p::protocol::dcutr::Sync* PROTOBUF_NULLABLE DCUtRMessage::unsafe_arena_release_sync() {
  // @@protoc_insertion_point(field_unsafe_arena_release:p2p.protocol.dcutr.DCUtRMessage.sync)
  if (payload_case() == kSync) {
    clear_has_payload();
    auto* temp = _impl_.payload_.sync_;
    _impl_.payload_.sync_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void DCUtRMessage::unsafe_arena_set_allocated_sync(
    ::p2p::protocol::dcutr::Sync* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_sync();
    _impl_.payload_.sync_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:p2p.protocol.dcutr.DCUtRMessage.sync)
}
inline ::p2p::protocol::dcutr::Sync* PROTOBUF_NONNULL DCUtRMessage::_internal_mutable_sync() {
  if (payload_case() != kSync) {
    clear_payload();
    set_has_sync();
    _impl_.payload_.sync_ = 
        ::google::protobuf::Message::DefaultConstruct<::p2p::protocol::dcutr::Sync>(GetArena());
  }
  return _impl_.payload_.sync_;
}
inline ::p2p::protocol::dcutr::Sync* PROTOBUF_NONNULL DCUtRMessage::mutable_sync()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::p2p::protocol::dcutr::Sync* _msg = _internal_mutable_sync();
  // @@protoc_insertion_point(field_mutable:p2p.protocol.dcutr.DCUtRMessage.sync)
  return _msg;
}

inline bool DCUtRMessage::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void DCUtRMessage::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline DCUtRMessage::PayloadCase DCUtRMessage::payload_case() const {
  return DCUtRMessage::PayloadCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// Connect

// repeated bytes addrs = 1;
inline int Connect::_internal_addrs_size() const {
  return _internal_addrs().size();
}
inline int Connect::addrs_size() const {
  return _internal_addrs_size();
}
inline void Connect::clear_addrs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.addrs_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::std::string* PROTOBUF_NONNULL Connect::add_addrs()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_addrs()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add_mutable:p2p.protocol.dcutr.Connect.addrs)
  return _s;
}
inline const ::std::string& Connect::addrs(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:p2p.protocol.dcutr.Connect.addrs)
  return _internal_addrs().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL Connect::mutable_addrs(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:p2p.protocol.dcutr.Connect.addrs)
  return _internal_mutable_addrs()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void Connect::set_addrs(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_addrs()->Mutable(index), ::std::forward<Arg_>(value),
                        args... , ::google::protobuf::internal::BytesTag{});
  // @@protoc_insertion_point(field_set:p2p.protocol.dcutr.Connect.addrs)
}
template <typename Arg_, typename... Args_>
inline void Connect::add_addrs(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_addrs(), ::std::forward<Arg_>(value),
      args... , ::google::protobuf::internal::BytesTag{});
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:p2p.protocol.dcutr.Connect.addrs)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& Connect::addrs()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:p2p.protocol.dcutr.Connect.addrs)
  return _internal_addrs();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
Connect::mutable_addrs() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:p2p.protocol.dcutr.Connect.addrs)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_addrs();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
Connect::_internal_addrs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.addrs_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
Connect::_internal_mutable_addrs() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.addrs_;
}

// int64 timestamp_ns = 2;
inline void Connect::clear_timestamp_ns() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ns_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int64_t Connect::timestamp_ns() const {
  // @@protoc_insertion_point(field_get:p2p.protocol.dcutr.Connect.timestamp_ns)
  return _internal_timestamp_ns();
}
inline void Connect::set_timestamp_ns(::int64_t value) {
  _internal_set_timestamp_ns(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:p2p.protocol.dcutr.Connect.timestamp_ns)
}
inline ::int64_t Connect::_internal_timestamp_ns() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_ns_;
}
inline void Connect::_internal_set_timestamp_ns(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ns_ = value;
}

// -------------------------------------------------------------------

// Sync

// repeated bytes addrs = 1;
inline int Sync::_internal_addrs_size() const {
  return _internal_addrs().size();
}
inline int Sync::addrs_size() const {
  return _internal_addrs_size();
}
inline void Sync::clear_addrs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.addrs_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::std::string* PROTOBUF_NONNULL Sync::add_addrs()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_addrs()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add_mutable:p2p.protocol.dcutr.Sync.addrs)
  return _s;
}
inline const ::std::string& Sync::addrs(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:p2p.protocol.dcutr.Sync.addrs)
  return _internal_addrs().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL Sync::mutable_addrs(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:p2p.protocol.dcutr.Sync.addrs)
  return _internal_mutable_addrs()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void Sync::set_addrs(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_addrs()->Mutable(index), ::std::forward<Arg_>(value),
                        args... , ::google::protobuf::internal::BytesTag{});
  // @@protoc_insertion_point(field_set:p2p.protocol.dcutr.Sync.addrs)
}
template <typename Arg_, typename... Args_>
inline void Sync::add_addrs(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_addrs(), ::std::forward<Arg_>(value),
      args... , ::google::protobuf::internal::BytesTag{});
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:p2p.protocol.dcutr.Sync.addrs)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& Sync::addrs()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:p2p.protocol.dcutr.Sync.addrs)
  return _internal_addrs();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
Sync::mutable_addrs() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:p2p.protocol.dcutr.Sync.addrs)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_addrs();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
Sync::_internal_addrs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.addrs_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
Sync::_internal_mutable_addrs() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.addrs_;
}

// int64 echo_timestamp_ns = 2;
inline void Sync::clear_echo_timestamp_ns() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.echo_timestamp_ns_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int64_t Sync::echo_timestamp_ns() const {
  // @@protoc_insertion_point(field_get:p2p.protocol.dcutr.Sync.echo_timestamp_ns)
  return _internal_echo_timestamp_ns();
}
inline void Sync::set_echo_timestamp_ns(::int64_t value) {
  _internal_set_echo_timestamp_ns(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:p2p.protocol.dcutr.Sync.echo_timestamp_ns)
}
inline ::int64_t Sync::_internal_echo_timestamp_ns() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.echo_timestamp_ns_;
}
inline void Sync::_internal_set_echo_timestamp_ns(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.echo_timestamp_ns_ = value;
}

// int64 timestamp_ns = 3;
inline void Sync::clear_timestamp_ns() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ns_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int64_t Sync::timestamp_ns() const {
  // @@protoc_insertion_point(field_get:p2p.protocol.dcutr.Sync.timestamp_ns)
  return _internal_timestamp_ns();
}
inline void Sync::set_timestamp_ns(::int64_t value) {
  _internal_set_timestamp_ns(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:p2p.protocol.dcutr.Sync.timestamp_ns)
}
inline ::int64_t Sync::_internal_timestamp_ns() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_ns_;
}
inline void Sync::_internal_set_timestamp_ns(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ns_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace dcutr
}  // namespace protocol
}  // namespace p2p


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::p2p::protocol::dcutr::DCUtRMessage_Type> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::p2p::protocol::dcutr::DCUtRMessage_Type>() {
  return ::p2p::protocol::dcutr::DCUtRMessage_Type_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // proto_2fdcutr_2eproto_2epb_2eh
