// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/dcutr.proto
// Protobuf C++ Version: 6.33.4

#include "proto/dcutr.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace p2p {
namespace protocol {
namespace dcutr {

inline constexpr Sync::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        addrs_{},
        echo_timestamp_ns_{::int64_t{0}},
        timestamp_ns_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR Sync::Sync(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Sync_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SyncDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SyncDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SyncDefaultTypeInternal() {}
  union {
    Sync _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SyncDefaultTypeInternal _Sync_default_instance_;

inline constexpr Connect::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        addrs_{},
        timestamp_ns_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR Connect::Connect(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Connect_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ConnectDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ConnectDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ConnectDefaultTypeInternal() {}
  union {
    Connect _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ConnectDefaultTypeInternal _Connect_default_instance_;

inline constexpr DCUtRMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        type_{static_cast< ::p2p::protocol::dcutr::DCUtRMessage_Type >(0)},
        payload_{},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR DCUtRMessage::DCUtRMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(DCUtRMessage_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DCUtRMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DCUtRMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DCUtRMessageDefaultTypeInternal() {}
  union {
    DCUtRMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DCUtRMessageDefaultTypeInternal _DCUtRMessage_default_instance_;
}  // namespace dcutr
}  // namespace protocol
}  // namespace p2p
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_proto_2fdcutr_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_proto_2fdcutr_2eproto = nullptr;
const ::uint32_t
    TableStruct_proto_2fdcutr_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x085, // bitmap
        PROTOBUF_FIELD_OFFSET(::p2p::protocol::dcutr::DCUtRMessage, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::p2p::protocol::dcutr::DCUtRMessage, _impl_._oneof_case_[0]),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::p2p::protocol::dcutr::DCUtRMessage, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::p2p::protocol::dcutr::DCUtRMessage, _impl_.payload_),
        PROTOBUF_FIELD_OFFSET(::p2p::protocol::dcutr::DCUtRMessage, _impl_.payload_),
        PROTOBUF_FIELD_OFFSET(::p2p::protocol::dcutr::DCUtRMessage, _impl_.payload_),
        0,
        ~0u,
        ~0u,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::p2p::protocol::dcutr::Connect, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::p2p::protocol::dcutr::Connect, _impl_.addrs_),
        PROTOBUF_FIELD_OFFSET(::p2p::protocol::dcutr::Connect, _impl_.timestamp_ns_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::p2p::protocol::dcutr::Sync, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::p2p::protocol::dcutr::Sync, _impl_.addrs_),
        PROTOBUF_FIELD_OFFSET(::p2p::protocol::dcutr::Sync, _impl_.echo_timestamp_ns_),
        PROTOBUF_FIELD_OFFSET(::p2p::protocol::dcutr::Sync, _impl_.timestamp_ns_),
        0,
        1,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::p2p::protocol::dcutr::DCUtRMessage)},
        {11, sizeof(::p2p::protocol::dcutr::Connect)},
        {18, sizeof(::p2p::protocol::dcutr::Sync)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::p2p::protocol::dcutr::_DCUtRMessage_default_instance_._instance,
    &::p2p::protocol::dcutr::_Connect_default_instance_._instance,
    &::p2p::protocol::dcutr::_Sync_default_instance_._instance,
};
const char descriptor_table_protodef_proto_2fdcutr_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021proto/dcutr.proto\022\022p2p.protocol.dcutr\""
    "\307\001\n\014DCUtRMessage\0223\n\004type\030\001 \001(\0162%.p2p.pro"
    "tocol.dcutr.DCUtRMessage.Type\022.\n\007connect"
    "\030\002 \001(\0132\033.p2p.protocol.dcutr.ConnectH\000\022(\n"
    "\004sync\030\003 \001(\0132\030.p2p.protocol.dcutr.SyncH\000\""
    "\035\n\004Type\022\013\n\007CONNECT\020\000\022\010\n\004SYNC\020\001B\t\n\007payloa"
    "d\".\n\007Connect\022\r\n\005addrs\030\001 \003(\014\022\024\n\014timestamp"
    "_ns\030\002 \001(\003\"F\n\004Sync\022\r\n\005addrs\030\001 \003(\014\022\031\n\021echo"
    "_timestamp_ns\030\002 \001(\003\022\024\n\014timestamp_ns\030\003 \001("
    "\003b\006proto3"
};
static ::absl::once_flag descriptor_table_proto_2fdcutr_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_proto_2fdcutr_2eproto = {
    false,
    false,
    369,
    descriptor_table_protodef_proto_2fdcutr_2eproto,
    "proto/dcutr.proto",
    &descriptor_table_proto_2fdcutr_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_proto_2fdcutr_2eproto::offsets,
    file_level_enum_descriptors_proto_2fdcutr_2eproto,
    file_level_service_descriptors_proto_2fdcutr_2eproto,
};
namespace p2p {
namespace protocol {
namespace dcutr {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL DCUtRMessage_Type_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_proto_2fdcutr_2eproto);
  return file_level_enum_descriptors_proto_2fdcutr_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t DCUtRMessage_Type_internal_data_[] = {
    131072u, 0u, };
// ===================================================================

class DCUtRMessage::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<DCUtRMessage>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(DCUtRMessage, _impl_._has_bits_);
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::p2p::protocol::dcutr::DCUtRMessage, _impl_._oneof_case_);
};

void DCUtRMessage::set_allocated_connect(::p2p::protocol::dcutr::Connect* PROTOBUF_NULLABLE connect) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (connect) {
    ::google::protobuf::Arena* submessage_arena = connect->GetArena();
    if (message_arena != submessage_arena) {
      connect = ::google::protobuf::internal::GetOwnedMessage(message_arena, connect, submessage_arena);
    }
    set_has_connect();
    _impl_.payload_.connect_ = connect;
  }
  // @@protoc_insertion_point(field_set_allocated:p2p.protocol.dcutr.DCUtRMessage.connect)
}
void DCUtRMessage::set_allocated_sync(::p2p::protocol::dcutr::Sync* PROTOBUF_NULLABLE sync) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (sync) {
    ::google::protobuf::Arena* submessage_arena = sync->GetArena();
    if (message_arena != submessage_arena) {
      sync = ::google::protobuf::internal::GetOwnedMessage(message_arena, sync, submessage_arena);
    }
    set_has_sync();
    _impl_.payload_.sync_ = sync;
  }
  // @@protoc_insertion_point(field_set_allocated:p2p.protocol.dcutr.DCUtRMessage.sync)
}
DCUtRMessage::DCUtRMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, DCUtRMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:p2p.protocol.dcutr.DCUtRMessage)
}
PROTOBUF_NDEBUG_INLINE DCUtRMessage::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::p2p::protocol::dcutr::DCUtRMessage& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        payload_{},
        _oneof_case_{from._oneof_case_[0]} {}

DCUtRMessage::DCUtRMessage(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const DCUtRMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, DCUtRMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  DCUtRMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.type_ = from._impl_.type_;
  switch (payload_case()) {
    case PAYLOAD_NOT_SET:
      break;
      case kConnect:
        _impl_.payload_.connect_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.connect_);
        break;
      case kSync:
        _impl_.payload_.sync_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.sync_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:p2p.protocol.dcutr.DCUtRMessage)
}
PROTOBUF_NDEBUG_INLINE DCUtRMessage::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        payload_{},
        _oneof_case_{} {}

inline void DCUtRMessage::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.type_ = {};
}
DCUtRMessage::~DCUtRMessage() {
  // @@protoc_insertion_point(destructor:p2p.protocol.dcutr.DCUtRMessage)
  SharedDtor(*this);
}
inline void DCUtRMessage::SharedDtor(MessageLite& self) {
  DCUtRMessage& this_ = static_cast<DCUtRMessage&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_payload()) {
    this_.clear_payload();
  }
  this_._impl_.~Impl_();
}

void DCUtRMessage::clear_payload() {
// @@protoc_insertion_point(one_of_clear_start:p2p.protocol.dcutr.DCUtRMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (payload_case()) {
    case kConnect: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.connect_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.connect_);
      }
      break;
    }
    case kSync: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.sync_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.sync_);
      }
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}


inline void* PROTOBUF_NONNULL DCUtRMessage::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) DCUtRMessage(arena);
}
constexpr auto DCUtRMessage::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(DCUtRMessage),
                                            alignof(DCUtRMessage));
}
constexpr auto DCUtRMessage::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_DCUtRMessage_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &DCUtRMessage::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<DCUtRMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &DCUtRMessage::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<DCUtRMessage>(), &DCUtRMessage::ByteSizeLong,
              &DCUtRMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(DCUtRMessage, _impl_._cached_size_),
          false,
      },
      &DCUtRMessage::kDescriptorMethods,
      &descriptor_table_proto_2fdcutr_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull DCUtRMessage_class_data_ =
        DCUtRMessage::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
DCUtRMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&DCUtRMessage_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(DCUtRMessage_class_data_.tc_table);
  return DCUtRMessage_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 3, 2, 0, 2>
DCUtRMessage::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(DCUtRMessage, _impl_._has_bits_),
    0, // no _extensions_
    3, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    DCUtRMessage_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::p2p::protocol::dcutr::DCUtRMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .p2p.protocol.dcutr.DCUtRMessage.Type type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DCUtRMessage, _impl_.type_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(DCUtRMessage, _impl_.type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .p2p.protocol.dcutr.DCUtRMessage.Type type = 1;
    {PROTOBUF_FIELD_OFFSET(DCUtRMessage, _impl_.type_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // .p2p.protocol.dcutr.Connect connect = 2;
    {PROTOBUF_FIELD_OFFSET(DCUtRMessage, _impl_.payload_.connect_), _Internal::kOneofCaseOffset + 0, 0, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .p2p.protocol.dcutr.Sync sync = 3;
    {PROTOBUF_FIELD_OFFSET(DCUtRMessage, _impl_.payload_.sync_), _Internal::kOneofCaseOffset + 0, 1, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::p2p::protocol::dcutr::Connect>()},
      {::_pbi::TcParser::GetTable<::p2p::protocol::dcutr::Sync>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void DCUtRMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:p2p.protocol.dcutr.DCUtRMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.type_ = 0;
  clear_payload();
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL DCUtRMessage::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const DCUtRMessage& this_ = static_cast<const DCUtRMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL DCUtRMessage::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const DCUtRMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:p2p.protocol.dcutr.DCUtRMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .p2p.protocol.dcutr.DCUtRMessage.Type type = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_type() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_type(), target);
    }
  }

  switch (this_.payload_case()) {
    case kConnect: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          2, *this_._impl_.payload_.connect_, this_._impl_.payload_.connect_->GetCachedSize(), target,
          stream);
      break;
    }
    case kSync: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          3, *this_._impl_.payload_.sync_, this_._impl_.payload_.sync_->GetCachedSize(), target,
          stream);
      break;
    }
    default:
      break;
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:p2p.protocol.dcutr.DCUtRMessage)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t DCUtRMessage::ByteSizeLong(const MessageLite& base) {
  const DCUtRMessage& this_ = static_cast<const DCUtRMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t DCUtRMessage::ByteSizeLong() const {
  const DCUtRMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:p2p.protocol.dcutr.DCUtRMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // .p2p.protocol.dcutr.DCUtRMessage.Type type = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_type() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_type());
      }
    }
  }
  switch (this_.payload_case()) {
    // .p2p.protocol.dcutr.Connect connect = 2;
    case kConnect: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.connect_);
      break;
    }
    // .p2p.protocol.dcutr.Sync sync = 3;
    case kSync: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.sync_);
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void DCUtRMessage::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<DCUtRMessage*>(&to_msg);
  auto& from = static_cast<const DCUtRMessage&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:p2p.protocol.dcutr.DCUtRMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (from._internal_type() != 0) {
      _this->_impl_.type_ = from._impl_.type_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  if (const uint32_t oneof_from_case =
          from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_payload();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kConnect: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.connect_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.connect_);
        } else {
          _this->_impl_.payload_.connect_->MergeFrom(*from._impl_.payload_.connect_);
        }
        break;
      }
      case kSync: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.sync_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.sync_);
        } else {
          _this->_impl_.payload_.sync_->MergeFrom(*from._impl_.payload_.sync_);
        }
        break;
      }
      case PAYLOAD_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void DCUtRMessage::CopyFrom(const DCUtRMessage& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:p2p.protocol.dcutr.DCUtRMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DCUtRMessage::InternalSwap(DCUtRMessage* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.type_, other->_impl_.type_);
  swap(_impl_.payload_, other->_impl_.payload_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata DCUtRMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Connect::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Connect>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Connect, _impl_._has_bits_);
};

Connect::Connect(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Connect_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:p2p.protocol.dcutr.Connect)
}
PROTOBUF_NDEBUG_INLINE Connect::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::p2p::protocol::dcutr::Connect& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        addrs_{visibility, arena, from.addrs_} {}

Connect::Connect(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Connect& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Connect_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Connect* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.timestamp_ns_ = from._impl_.timestamp_ns_;

  // @@protoc_insertion_point(copy_constructor:p2p.protocol.dcutr.Connect)
}
PROTOBUF_NDEBUG_INLINE Connect::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        addrs_{visibility, arena} {}

inline void Connect::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.timestamp_ns_ = {};
}
Connect::~Connect() {
  // @@protoc_insertion_point(destructor:p2p.protocol.dcutr.Connect)
  SharedDtor(*this);
}
inline void Connect::SharedDtor(MessageLite& self) {
  Connect& this_ = static_cast<Connect&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Connect::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Connect(arena);
}
constexpr auto Connect::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Connect, _impl_.addrs_) +
          decltype(Connect::_impl_.addrs_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(Connect), alignof(Connect), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Connect::PlacementNew_,
                                 sizeof(Connect),
                                 alignof(Connect));
  }
}
constexpr auto Connect::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Connect_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Connect::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Connect>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Connect::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Connect>(), &Connect::ByteSizeLong,
              &Connect::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Connect, _impl_._cached_size_),
          false,
      },
      &Connect::kDescriptorMethods,
      &descriptor_table_proto_2fdcutr_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Connect_class_data_ =
        Connect::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Connect::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Connect_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Connect_class_data_.tc_table);
  return Connect_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
Connect::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Connect, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Connect_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::p2p::protocol::dcutr::Connect>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int64 timestamp_ns = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Connect, _impl_.timestamp_ns_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(Connect, _impl_.timestamp_ns_)}},
    // repeated bytes addrs = 1;
    {::_pbi::TcParser::FastBR1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(Connect, _impl_.addrs_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated bytes addrs = 1;
    {PROTOBUF_FIELD_OFFSET(Connect, _impl_.addrs_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kBytes | ::_fl::kRepSString)},
    // int64 timestamp_ns = 2;
    {PROTOBUF_FIELD_OFFSET(Connect, _impl_.timestamp_ns_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void Connect::Clear() {
// @@protoc_insertion_point(message_clear_start:p2p.protocol.dcutr.Connect)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _impl_.addrs_.Clear();
  }
  _impl_.timestamp_ns_ = ::int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Connect::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Connect& this_ = static_cast<const Connect&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Connect::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Connect& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:p2p.protocol.dcutr.Connect)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated bytes addrs = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (int i = 0, n = this_._internal_addrs_size(); i < n; ++i) {
      const auto& s = this_._internal_addrs().Get(i);
      target = stream->WriteBytes(1, s, target);
    }
  }

  // int64 timestamp_ns = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_timestamp_ns() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<2>(
              stream, this_._internal_timestamp_ns(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:p2p.protocol.dcutr.Connect)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Connect::ByteSizeLong(const MessageLite& base) {
  const Connect& this_ = static_cast<const Connect&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Connect::ByteSizeLong() const {
  const Connect& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:p2p.protocol.dcutr.Connect)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // repeated bytes addrs = 1;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_addrs().size());
      for (int i = 0, n = this_._internal_addrs().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
            this_._internal_addrs().Get(i));
      }
    }
    // int64 timestamp_ns = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_timestamp_ns() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_timestamp_ns());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Connect::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Connect*>(&to_msg);
  auto& from = static_cast<const Connect&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:p2p.protocol.dcutr.Connect)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_addrs()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_addrs());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_timestamp_ns() != 0) {
        _this->_impl_.timestamp_ns_ = from._impl_.timestamp_ns_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Connect::CopyFrom(const Connect& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:p2p.protocol.dcutr.Connect)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Connect::InternalSwap(Connect* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.addrs_.InternalSwap(&other->_impl_.addrs_);
  swap(_impl_.timestamp_ns_, other->_impl_.timestamp_ns_);
}

::google::protobuf::Metadata Connect::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Sync::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Sync>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Sync, _impl_._has_bits_);
};

Sync::Sync(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Sync_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:p2p.protocol.dcutr.Sync)
}
PROTOBUF_NDEBUG_INLINE Sync::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::p2p::protocol::dcutr::Sync& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        addrs_{visibility, arena, from.addrs_} {}

Sync::Sync(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Sync& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Sync_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Sync* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, echo_timestamp_ns_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, echo_timestamp_ns_),
           offsetof(Impl_, timestamp_ns_) -
               offsetof(Impl_, echo_timestamp_ns_) +
               sizeof(Impl_::timestamp_ns_));

  // @@protoc_insertion_point(copy_constructor:p2p.protocol.dcutr.Sync)
}
PROTOBUF_NDEBUG_INLINE Sync::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        addrs_{visibility, arena} {}

inline void Sync::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, echo_timestamp_ns_),
           0,
           offsetof(Impl_, timestamp_ns_) -
               offsetof(Impl_, echo_timestamp_ns_) +
               sizeof(Impl_::timestamp_ns_));
}
Sync::~Sync() {
  // @@protoc_insertion_point(destructor:p2p.protocol.dcutr.Sync)
  SharedDtor(*this);
}
inline void Sync::SharedDtor(MessageLite& self) {
  Sync& this_ = static_cast<Sync&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Sync::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Sync(arena);
}
constexpr auto Sync::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Sync, _impl_.addrs_) +
          decltype(Sync::_impl_.addrs_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(Sync), alignof(Sync), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Sync::PlacementNew_,
                                 sizeof(Sync),
                                 alignof(Sync));
  }
}
constexpr auto Sync::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Sync_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Sync::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Sync>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Sync::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Sync>(), &Sync::ByteSizeLong,
              &Sync::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Sync, _impl_._cached_size_),
          false,
      },
      &Sync::kDescriptorMethods,
      &descriptor_table_proto_2fdcutr_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Sync_class_data_ =
        Sync::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Sync::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Sync_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Sync_class_data_.tc_table);
  return Sync_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
Sync::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Sync, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Sync_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::p2p::protocol::dcutr::Sync>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // repeated bytes addrs = 1;
    {::_pbi::TcParser::FastBR1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(Sync, _impl_.addrs_)}},
    // int64 echo_timestamp_ns = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Sync, _impl_.echo_timestamp_ns_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(Sync, _impl_.echo_timestamp_ns_)}},
    // int64 timestamp_ns = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Sync, _impl_.timestamp_ns_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(Sync, _impl_.timestamp_ns_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated bytes addrs = 1;
    {PROTOBUF_FIELD_OFFSET(Sync, _impl_.addrs_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kBytes | ::_fl::kRepSString)},
    // int64 echo_timestamp_ns = 2;
    {PROTOBUF_FIELD_OFFSET(Sync, _impl_.echo_timestamp_ns_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // int64 timestamp_ns = 3;
    {PROTOBUF_FIELD_OFFSET(Sync, _impl_.timestamp_ns_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void Sync::Clear() {
// @@protoc_insertion_point(message_clear_start:p2p.protocol.dcutr.Sync)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _impl_.addrs_.Clear();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000006U)) {
    ::memset(&_impl_.echo_timestamp_ns_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.timestamp_ns_) -
        reinterpret_cast<char*>(&_impl_.echo_timestamp_ns_)) + sizeof(_impl_.timestamp_ns_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Sync::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Sync& this_ = static_cast<const Sync&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Sync::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Sync& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:p2p.protocol.dcutr.Sync)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated bytes addrs = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (int i = 0, n = this_._internal_addrs_size(); i < n; ++i) {
      const auto& s = this_._internal_addrs().Get(i);
      target = stream->WriteBytes(1, s, target);
    }
  }

  // int64 echo_timestamp_ns = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_echo_timestamp_ns() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<2>(
              stream, this_._internal_echo_timestamp_ns(), target);
    }
  }

  // int64 timestamp_ns = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_timestamp_ns() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<3>(
              stream, this_._internal_timestamp_ns(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:p2p.protocol.dcutr.Sync)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Sync::ByteSizeLong(const MessageLite& base) {
  const Sync& this_ = static_cast<const Sync&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Sync::ByteSizeLong() const {
  const Sync& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:p2p.protocol.dcutr.Sync)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // repeated bytes addrs = 1;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_addrs().size());
      for (int i = 0, n = this_._internal_addrs().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
            this_._internal_addrs().Get(i));
      }
    }
    // int64 echo_timestamp_ns = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_echo_timestamp_ns() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_echo_timestamp_ns());
      }
    }
    // int64 timestamp_ns = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_timestamp_ns() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_timestamp_ns());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Sync::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Sync*>(&to_msg);
  auto& from = static_cast<const Sync&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:p2p.protocol.dcutr.Sync)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_addrs()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_addrs());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_echo_timestamp_ns() != 0) {
        _this->_impl_.echo_timestamp_ns_ = from._impl_.echo_timestamp_ns_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_timestamp_ns() != 0) {
        _this->_impl_.timestamp_ns_ = from._impl_.timestamp_ns_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Sync::CopyFrom(const Sync& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:p2p.protocol.dcutr.Sync)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Sync::InternalSwap(Sync* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.addrs_.InternalSwap(&other->_impl_.addrs_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Sync, _impl_.timestamp_ns_)
      + sizeof(Sync::_impl_.timestamp_ns_)
      - PROTOBUF_FIELD_OFFSET(Sync, _impl_.echo_timestamp_ns_)>(
          reinterpret_cast<char*>(&_impl_.echo_timestamp_ns_),
          reinterpret_cast<char*>(&other->_impl_.echo_timestamp_ns_));
}

::google::protobuf::Metadata Sync::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace dcutr
}  // namespace protocol
}  // namespace p2p
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_proto_2fdcutr_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
