// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/relay_v2.proto
// Protobuf C++ Version: 6.33.4

#ifndef proto_2frelay_5fv2_2eproto_2epb_2eh
#define proto_2frelay_5fv2_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_proto_2frelay_5fv2_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2frelay_5fv2_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_proto_2frelay_5fv2_2eproto;
}  // extern "C"
namespace p2p {
namespace relay {
namespace v2 {
enum CircuitRelay_Type : int;
extern const uint32_t CircuitRelay_Type_internal_data_[];
enum Status_Code : int;
extern const uint32_t Status_Code_internal_data_[];
class CircuitRelay;
struct CircuitRelayDefaultTypeInternal;
extern CircuitRelayDefaultTypeInternal _CircuitRelay_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CircuitRelay_class_data_;
class Peer;
struct PeerDefaultTypeInternal;
extern PeerDefaultTypeInternal _Peer_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Peer_class_data_;
class Reservation;
struct ReservationDefaultTypeInternal;
extern ReservationDefaultTypeInternal _Reservation_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Reservation_class_data_;
class ReservationVoucher;
struct ReservationVoucherDefaultTypeInternal;
extern ReservationVoucherDefaultTypeInternal _ReservationVoucher_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ReservationVoucher_class_data_;
class Status;
struct StatusDefaultTypeInternal;
extern StatusDefaultTypeInternal _Status_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Status_class_data_;
}  // namespace v2
}  // namespace relay
}  // namespace p2p
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::p2p::relay::v2::CircuitRelay_Type_internal_data_>
    internal::EnumTraitsImpl::value<::p2p::relay::v2::CircuitRelay_Type>;
template <>
internal::EnumTraitsT<::p2p::relay::v2::Status_Code_internal_data_>
    internal::EnumTraitsImpl::value<::p2p::relay::v2::Status_Code>;
}  // namespace protobuf
}  // namespace google

namespace p2p {
namespace relay {
namespace v2 {
enum CircuitRelay_Type : int {
  CircuitRelay_Type_RESERVE = 0,
  CircuitRelay_Type_CONNECT = 1,
  CircuitRelay_Type_STATUS = 2,
  CircuitRelay_Type_CircuitRelay_Type_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  CircuitRelay_Type_CircuitRelay_Type_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t CircuitRelay_Type_internal_data_[];
inline constexpr CircuitRelay_Type CircuitRelay_Type_Type_MIN =
    static_cast<CircuitRelay_Type>(0);
inline constexpr CircuitRelay_Type CircuitRelay_Type_Type_MAX =
    static_cast<CircuitRelay_Type>(2);
inline bool CircuitRelay_Type_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int CircuitRelay_Type_Type_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL CircuitRelay_Type_descriptor();
template <typename T>
const ::std::string& CircuitRelay_Type_Name(T value) {
  static_assert(::std::is_same<T, CircuitRelay_Type>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Type_Name().");
  return CircuitRelay_Type_Name(static_cast<CircuitRelay_Type>(value));
}
template <>
inline const ::std::string& CircuitRelay_Type_Name(CircuitRelay_Type value) {
  return ::google::protobuf::internal::NameOfDenseEnum<CircuitRelay_Type_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool CircuitRelay_Type_Parse(
    ::absl::string_view name, CircuitRelay_Type* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<CircuitRelay_Type>(CircuitRelay_Type_descriptor(), name,
                                           value);
}
enum Status_Code : int {
  Status_Code_OK = 0,
  Status_Code_RESERVATION_REFUSED = 1,
  Status_Code_RESOURCE_LIMIT_EXCEEDED = 2,
  Status_Code_PERMISSION_DENIED = 3,
  Status_Code_CONNECTION_FAILED = 4,
  Status_Code_NO_RESERVATION = 5,
  Status_Code_MALFORMED_MESSAGE = 6,
  Status_Code_UNEXPECTED_MESSAGE = 7,
  Status_Code_Status_Code_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  Status_Code_Status_Code_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t Status_Code_internal_data_[];
inline constexpr Status_Code Status_Code_Code_MIN =
    static_cast<Status_Code>(0);
inline constexpr Status_Code Status_Code_Code_MAX =
    static_cast<Status_Code>(7);
inline bool Status_Code_IsValid(int value) {
  return 0 <= value && value <= 7;
}
inline constexpr int Status_Code_Code_ARRAYSIZE = 7 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Status_Code_descriptor();
template <typename T>
const ::std::string& Status_Code_Name(T value) {
  static_assert(::std::is_same<T, Status_Code>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Code_Name().");
  return Status_Code_Name(static_cast<Status_Code>(value));
}
template <>
inline const ::std::string& Status_Code_Name(Status_Code value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Status_Code_descriptor, 0, 7>(
      static_cast<int>(value));
}
inline bool Status_Code_Parse(
    ::absl::string_view name, Status_Code* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<Status_Code>(Status_Code_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class Status final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:p2p.relay.v2.Status) */ {
 public:
  inline Status() : Status(nullptr) {}
  ~Status() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Status* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Status));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Status(::google::protobuf::internal::ConstantInitialized);

  inline Status(const Status& from) : Status(nullptr, from) {}
  inline Status(Status&& from) noexcept
      : Status(nullptr, ::std::move(from)) {}
  inline Status& operator=(const Status& from) {
    CopyFrom(from);
    return *this;
  }
  inline Status& operator=(Status&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Status& default_instance() {
    return *reinterpret_cast<const Status*>(
        &_Status_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(Status& a, Status& b) { a.Swap(&b); }
  inline void Swap(Status* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Status* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Status* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Status>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Status& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Status& from) { Status::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Status* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "p2p.relay.v2.Status"; }

  explicit Status(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Status(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Status& from);
  Status(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Status&& from) noexcept
      : Status(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Code = Status_Code;
  static constexpr Code OK = Status_Code_OK;
  static constexpr Code RESERVATION_REFUSED = Status_Code_RESERVATION_REFUSED;
  static constexpr Code RESOURCE_LIMIT_EXCEEDED = Status_Code_RESOURCE_LIMIT_EXCEEDED;
  static constexpr Code PERMISSION_DENIED = Status_Code_PERMISSION_DENIED;
  static constexpr Code CONNECTION_FAILED = Status_Code_CONNECTION_FAILED;
  static constexpr Code NO_RESERVATION = Status_Code_NO_RESERVATION;
  static constexpr Code MALFORMED_MESSAGE = Status_Code_MALFORMED_MESSAGE;
  static constexpr Code UNEXPECTED_MESSAGE = Status_Code_UNEXPECTED_MESSAGE;
  static inline bool Code_IsValid(int value) {
    return Status_Code_IsValid(value);
  }
  static constexpr Code Code_MIN = Status_Code_Code_MIN;
  static constexpr Code Code_MAX = Status_Code_Code_MAX;
  static constexpr int Code_ARRAYSIZE = Status_Code_Code_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Code_descriptor() {
    return Status_Code_descriptor();
  }
  template <typename T>
  static inline const ::std::string& Code_Name(T value) {
    return Status_Code_Name(value);
  }
  static inline bool Code_Parse(
      ::absl::string_view name, Code* PROTOBUF_NONNULL value) {
    return Status_Code_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kTextFieldNumber = 2,
    kCodeFieldNumber = 1,
  };
  // string text = 2;
  void clear_text() ;
  const ::std::string& text() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_text(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_text();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_text();
  void set_allocated_text(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_text() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_text(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_text();

  public:
  // .p2p.relay.v2.Status.Code code = 1;
  void clear_code() ;
  ::p2p::relay::v2::Status_Code code() const;
  void set_code(::p2p::relay::v2::Status_Code value);

  private:
  ::p2p::relay::v2::Status_Code _internal_code() const;
  void _internal_set_code(::p2p::relay::v2::Status_Code value);

  public:
  // @@protoc_insertion_point(class_scope:p2p.relay.v2.Status)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 32,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Status& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr text_;
    int code_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2frelay_5fv2_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Status_class_data_;
// -------------------------------------------------------------------

class ReservationVoucher final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:p2p.relay.v2.ReservationVoucher) */ {
 public:
  inline ReservationVoucher() : ReservationVoucher(nullptr) {}
  ~ReservationVoucher() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ReservationVoucher* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ReservationVoucher));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ReservationVoucher(::google::protobuf::internal::ConstantInitialized);

  inline ReservationVoucher(const ReservationVoucher& from) : ReservationVoucher(nullptr, from) {}
  inline ReservationVoucher(ReservationVoucher&& from) noexcept
      : ReservationVoucher(nullptr, ::std::move(from)) {}
  inline ReservationVoucher& operator=(const ReservationVoucher& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReservationVoucher& operator=(ReservationVoucher&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReservationVoucher& default_instance() {
    return *reinterpret_cast<const ReservationVoucher*>(
        &_ReservationVoucher_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(ReservationVoucher& a, ReservationVoucher& b) { a.Swap(&b); }
  inline void Swap(ReservationVoucher* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReservationVoucher* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReservationVoucher* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ReservationVoucher>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ReservationVoucher& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ReservationVoucher& from) { ReservationVoucher::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ReservationVoucher* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "p2p.relay.v2.ReservationVoucher"; }

  explicit ReservationVoucher(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ReservationVoucher(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ReservationVoucher& from);
  ReservationVoucher(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ReservationVoucher&& from) noexcept
      : ReservationVoucher(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRelayFieldNumber = 1,
    kPeerFieldNumber = 2,
    kExpirationFieldNumber = 3,
  };
  // bytes relay = 1;
  void clear_relay() ;
  const ::std::string& relay() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_relay(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_relay();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_relay();
  void set_allocated_relay(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_relay() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_relay(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_relay();

  public:
  // bytes peer = 2;
  void clear_peer() ;
  const ::std::string& peer() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_peer(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_peer();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_peer();
  void set_allocated_peer(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_peer() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_peer(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_peer();

  public:
  // uint64 expiration = 3;
  void clear_expiration() ;
  ::uint64_t expiration() const;
  void set_expiration(::uint64_t value);

  private:
  ::uint64_t _internal_expiration() const;
  void _internal_set_expiration(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:p2p.relay.v2.ReservationVoucher)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ReservationVoucher& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr relay_;
    ::google::protobuf::internal::ArenaStringPtr peer_;
    ::uint64_t expiration_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2frelay_5fv2_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ReservationVoucher_class_data_;
// -------------------------------------------------------------------

class Reservation final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:p2p.relay.v2.Reservation) */ {
 public:
  inline Reservation() : Reservation(nullptr) {}
  ~Reservation() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Reservation* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Reservation));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Reservation(::google::protobuf::internal::ConstantInitialized);

  inline Reservation(const Reservation& from) : Reservation(nullptr, from) {}
  inline Reservation(Reservation&& from) noexcept
      : Reservation(nullptr, ::std::move(from)) {}
  inline Reservation& operator=(const Reservation& from) {
    CopyFrom(from);
    return *this;
  }
  inline Reservation& operator=(Reservation&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Reservation& default_instance() {
    return *reinterpret_cast<const Reservation*>(
        &_Reservation_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Reservation& a, Reservation& b) { a.Swap(&b); }
  inline void Swap(Reservation* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Reservation* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Reservation* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Reservation>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Reservation& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Reservation& from) { Reservation::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Reservation* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "p2p.relay.v2.Reservation"; }

  explicit Reservation(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Reservation(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Reservation& from);
  Reservation(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Reservation&& from) noexcept
      : Reservation(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAddrFieldNumber = 2,
    kVoucherFieldNumber = 3,
    kExpireFieldNumber = 1,
    kLimitDurationFieldNumber = 4,
    kLimitDataFieldNumber = 5,
  };
  // bytes addr = 2;
  void clear_addr() ;
  const ::std::string& addr() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_addr(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_addr();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_addr();
  void set_allocated_addr(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_addr() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_addr(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_addr();

  public:
  // bytes voucher = 3;
  void clear_voucher() ;
  const ::std::string& voucher() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_voucher(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_voucher();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_voucher();
  void set_allocated_voucher(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_voucher() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_voucher(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_voucher();

  public:
  // uint64 expire = 1;
  void clear_expire() ;
  ::uint64_t expire() const;
  void set_expire(::uint64_t value);

  private:
  ::uint64_t _internal_expire() const;
  void _internal_set_expire(::uint64_t value);

  public:
  // uint64 limit_duration = 4;
  void clear_limit_duration() ;
  ::uint64_t limit_duration() const;
  void set_limit_duration(::uint64_t value);

  private:
  ::uint64_t _internal_limit_duration() const;
  void _internal_set_limit_duration(::uint64_t value);

  public:
  // uint64 limit_data = 5;
  void clear_limit_data() ;
  ::uint64_t limit_data() const;
  void set_limit_data(::uint64_t value);

  private:
  ::uint64_t _internal_limit_data() const;
  void _internal_set_limit_data(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:p2p.relay.v2.Reservation)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Reservation& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr addr_;
    ::google::protobuf::internal::ArenaStringPtr voucher_;
    ::uint64_t expire_;
    ::uint64_t limit_duration_;
    ::uint64_t limit_data_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2frelay_5fv2_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Reservation_class_data_;
// -------------------------------------------------------------------

class Peer final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:p2p.relay.v2.Peer) */ {
 public:
  inline Peer() : Peer(nullptr) {}
  ~Peer() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Peer* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Peer));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Peer(::google::protobuf::internal::ConstantInitialized);

  inline Peer(const Peer& from) : Peer(nullptr, from) {}
  inline Peer(Peer&& from) noexcept
      : Peer(nullptr, ::std::move(from)) {}
  inline Peer& operator=(const Peer& from) {
    CopyFrom(from);
    return *this;
  }
  inline Peer& operator=(Peer&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Peer& default_instance() {
    return *reinterpret_cast<const Peer*>(
        &_Peer_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(Peer& a, Peer& b) { a.Swap(&b); }
  inline void Swap(Peer* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Peer* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Peer* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Peer>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Peer& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Peer& from) { Peer::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Peer* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "p2p.relay.v2.Peer"; }

  explicit Peer(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Peer(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Peer& from);
  Peer(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Peer&& from) noexcept
      : Peer(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAddrsFieldNumber = 2,
    kIdFieldNumber = 1,
  };
  // repeated bytes addrs = 2;
  int addrs_size() const;
  private:
  int _internal_addrs_size() const;

  public:
  void clear_addrs() ;
  const ::std::string& addrs(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_addrs(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_addrs(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_addrs();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_addrs(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& addrs() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_addrs();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_addrs() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_addrs();

  public:
  // bytes id = 1;
  void clear_id() ;
  const ::std::string& id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_id();
  void set_allocated_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_id();

  public:
  // @@protoc_insertion_point(class_scope:p2p.relay.v2.Peer)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Peer& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField<::std::string> addrs_;
    ::google::protobuf::internal::ArenaStringPtr id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2frelay_5fv2_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Peer_class_data_;
// -------------------------------------------------------------------

class CircuitRelay final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:p2p.relay.v2.CircuitRelay) */ {
 public:
  inline CircuitRelay() : CircuitRelay(nullptr) {}
  ~CircuitRelay() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CircuitRelay* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CircuitRelay));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CircuitRelay(::google::protobuf::internal::ConstantInitialized);

  inline CircuitRelay(const CircuitRelay& from) : CircuitRelay(nullptr, from) {}
  inline CircuitRelay(CircuitRelay&& from) noexcept
      : CircuitRelay(nullptr, ::std::move(from)) {}
  inline CircuitRelay& operator=(const CircuitRelay& from) {
    CopyFrom(from);
    return *this;
  }
  inline CircuitRelay& operator=(CircuitRelay&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CircuitRelay& default_instance() {
    return *reinterpret_cast<const CircuitRelay*>(
        &_CircuitRelay_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CircuitRelay& a, CircuitRelay& b) { a.Swap(&b); }
  inline void Swap(CircuitRelay* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CircuitRelay* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CircuitRelay* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CircuitRelay>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CircuitRelay& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CircuitRelay& from) { CircuitRelay::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CircuitRelay* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "p2p.relay.v2.CircuitRelay"; }

  explicit CircuitRelay(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CircuitRelay(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CircuitRelay& from);
  CircuitRelay(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CircuitRelay&& from) noexcept
      : CircuitRelay(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Type = CircuitRelay_Type;
  static constexpr Type RESERVE = CircuitRelay_Type_RESERVE;
  static constexpr Type CONNECT = CircuitRelay_Type_CONNECT;
  static constexpr Type STATUS = CircuitRelay_Type_STATUS;
  static inline bool Type_IsValid(int value) {
    return CircuitRelay_Type_IsValid(value);
  }
  static constexpr Type Type_MIN = CircuitRelay_Type_Type_MIN;
  static constexpr Type Type_MAX = CircuitRelay_Type_Type_MAX;
  static constexpr int Type_ARRAYSIZE = CircuitRelay_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Type_descriptor() {
    return CircuitRelay_Type_descriptor();
  }
  template <typename T>
  static inline const ::std::string& Type_Name(T value) {
    return CircuitRelay_Type_Name(value);
  }
  static inline bool Type_Parse(
      ::absl::string_view name, Type* PROTOBUF_NONNULL value) {
    return CircuitRelay_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kReservationFieldNumber = 2,
    kPeerFieldNumber = 3,
    kStatusFieldNumber = 4,
    kTypeFieldNumber = 1,
  };
  // .p2p.relay.v2.Reservation reservation = 2;
  bool has_reservation() const;
  void clear_reservation() ;
  const ::p2p::relay::v2::Reservation& reservation() const;
  [[nodiscard]] ::p2p::relay::v2::Reservation* PROTOBUF_NULLABLE release_reservation();
  ::p2p::relay::v2::Reservation* PROTOBUF_NONNULL mutable_reservation();
  void set_allocated_reservation(::p2p::relay::v2::Reservation* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_reservation(::p2p::relay::v2::Reservation* PROTOBUF_NULLABLE value);
  ::p2p::relay::v2::Reservation* PROTOBUF_NULLABLE unsafe_arena_release_reservation();

  private:
  const ::p2p::relay::v2::Reservation& _internal_reservation() const;
  ::p2p::relay::v2::Reservation* PROTOBUF_NONNULL _internal_mutable_reservation();

  public:
  // .p2p.relay.v2.Peer peer = 3;
  bool has_peer() const;
  void clear_peer() ;
  const ::p2p::relay::v2::Peer& peer() const;
  [[nodiscard]] ::p2p::relay::v2::Peer* PROTOBUF_NULLABLE release_peer();
  ::p2p::relay::v2::Peer* PROTOBUF_NONNULL mutable_peer();
  void set_allocated_peer(::p2p::relay::v2::Peer* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_peer(::p2p::relay::v2::Peer* PROTOBUF_NULLABLE value);
  ::p2p::relay::v2::Peer* PROTOBUF_NULLABLE unsafe_arena_release_peer();

  private:
  const ::p2p::relay::v2::Peer& _internal_peer() const;
  ::p2p::relay::v2::Peer* PROTOBUF_NONNULL _internal_mutable_peer();

  public:
  // .p2p.relay.v2.Status status = 4;
  bool has_status() const;
  void clear_status() ;
  const ::p2p::relay::v2::Status& status() const;
  [[nodiscard]] ::p2p::relay::v2::Status* PROTOBUF_NULLABLE release_status();
  ::p2p::relay::v2::Status* PROTOBUF_NONNULL mutable_status();
  void set_allocated_status(::p2p::relay::v2::Status* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_status(::p2p::relay::v2::Status* PROTOBUF_NULLABLE value);
  ::p2p::relay::v2::Status* PROTOBUF_NULLABLE unsafe_arena_release_status();

  private:
  const ::p2p::relay::v2::Status& _internal_status() const;
  ::p2p::relay::v2::Status* PROTOBUF_NONNULL _internal_mutable_status();

  public:
  // .p2p.relay.v2.CircuitRelay.Type type = 1;
  void clear_type() ;
  ::p2p::relay::v2::CircuitRelay_Type type() const;
  void set_type(::p2p::relay::v2::CircuitRelay_Type value);

  private:
  ::p2p::relay::v2::CircuitRelay_Type _internal_type() const;
  void _internal_set_type(::p2p::relay::v2::CircuitRelay_Type value);

  public:
  // @@protoc_insertion_point(class_scope:p2p.relay.v2.CircuitRelay)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   3, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CircuitRelay& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::p2p::relay::v2::Reservation* PROTOBUF_NULLABLE reservation_;
    ::p2p::relay::v2::Peer* PROTOBUF_NULLABLE peer_;
    ::p2p::relay::v2::Status* PROTOBUF_NULLABLE status_;
    int type_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2frelay_5fv2_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CircuitRelay_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CircuitRelay

// .p2p.relay.v2.CircuitRelay.Type type = 1;
inline void CircuitRelay::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::p2p::relay::v2::CircuitRelay_Type CircuitRelay::type() const {
  // @@protoc_insertion_point(field_get:p2p.relay.v2.CircuitRelay.type)
  return _internal_type();
}
inline void CircuitRelay::set_type(::p2p::relay::v2::CircuitRelay_Type value) {
  _internal_set_type(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:p2p.relay.v2.CircuitRelay.type)
}
inline ::p2p::relay::v2::CircuitRelay_Type CircuitRelay::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::p2p::relay::v2::CircuitRelay_Type>(_impl_.type_);
}
inline void CircuitRelay::_internal_set_type(::p2p::relay::v2::CircuitRelay_Type value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// .p2p.relay.v2.Reservation reservation = 2;
inline bool CircuitRelay::has_reservation() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  PROTOBUF_ASSUME(!value || _impl_.reservation_ != nullptr);
  return value;
}
inline void CircuitRelay::clear_reservation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.reservation_ != nullptr) _impl_.reservation_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::p2p::relay::v2::Reservation& CircuitRelay::_internal_reservation() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::p2p::relay::v2::Reservation* p = _impl_.reservation_;
  return p != nullptr ? *p : reinterpret_cast<const ::p2p::relay::v2::Reservation&>(::p2p::relay::v2::_Reservation_default_instance_);
}
inline const ::p2p::relay::v2::Reservation& CircuitRelay::reservation() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:p2p.relay.v2.CircuitRelay.reservation)
  return _internal_reservation();
}
inline void CircuitRelay::unsafe_arena_set_allocated_reservation(
    ::p2p::relay::v2::Reservation* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.reservation_);
  }
  _impl_.reservation_ = reinterpret_cast<::p2p::relay::v2::Reservation*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:p2p.relay.v2.CircuitRelay.reservation)
}
inline ::p2p::relay::v2::Reservation* PROTOBUF_NULLABLE CircuitRelay::release_reservation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::p2p::relay::v2::Reservation* released = _impl_.reservation_;
  _impl_.reservation_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::p2p::relay::v2::Reservation* PROTOBUF_NULLABLE CircuitRelay::unsafe_arena_release_reservation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:p2p.relay.v2.CircuitRelay.reservation)

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::p2p::relay::v2::Reservation* temp = _impl_.reservation_;
  _impl_.reservation_ = nullptr;
  return temp;
}
inline ::p2p::relay::v2::Reservation* PROTOBUF_NONNULL CircuitRelay::_internal_mutable_reservation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.reservation_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::p2p::relay::v2::Reservation>(GetArena());
    _impl_.reservation_ = reinterpret_cast<::p2p::relay::v2::Reservation*>(p);
  }
  return _impl_.reservation_;
}
inline ::p2p::relay::v2::Reservation* PROTOBUF_NONNULL CircuitRelay::mutable_reservation()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::p2p::relay::v2::Reservation* _msg = _internal_mutable_reservation();
  // @@protoc_insertion_point(field_mutable:p2p.relay.v2.CircuitRelay.reservation)
  return _msg;
}
inline void CircuitRelay::set_allocated_reservation(::p2p::relay::v2::Reservation* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.reservation_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }

  _impl_.reservation_ = reinterpret_cast<::p2p::relay::v2::Reservation*>(value);
  // @@protoc_insertion_point(field_set_allocated:p2p.relay.v2.CircuitRelay.reservation)
}

// .p2p.relay.v2.Peer peer = 3;
inline bool CircuitRelay::has_peer() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.peer_ != nullptr);
  return value;
}
inline void CircuitRelay::clear_peer() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.peer_ != nullptr) _impl_.peer_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::p2p::relay::v2::Peer& CircuitRelay::_internal_peer() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::p2p::relay::v2::Peer* p = _impl_.peer_;
  return p != nullptr ? *p : reinterpret_cast<const ::p2p::relay::v2::Peer&>(::p2p::relay::v2::_Peer_default_instance_);
}
inline const ::p2p::relay::v2::Peer& CircuitRelay::peer() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:p2p.relay.v2.CircuitRelay.peer)
  return _internal_peer();
}
inline void CircuitRelay::unsafe_arena_set_allocated_peer(
    ::p2p::relay::v2::Peer* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.peer_);
  }
  _impl_.peer_ = reinterpret_cast<::p2p::relay::v2::Peer*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:p2p.relay.v2.CircuitRelay.peer)
}
inline ::p2p::relay::v2::Peer* PROTOBUF_NULLABLE CircuitRelay::release_peer() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::p2p::relay::v2::Peer* released = _impl_.peer_;
  _impl_.peer_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::p2p::relay::v2::Peer* PROTOBUF_NULLABLE CircuitRelay::unsafe_arena_release_peer() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:p2p.relay.v2.CircuitRelay.peer)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::p2p::relay::v2::Peer* temp = _impl_.peer_;
  _impl_.peer_ = nullptr;
  return temp;
}
inline ::p2p::relay::v2::Peer* PROTOBUF_NONNULL CircuitRelay::_internal_mutable_peer() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.peer_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::p2p::relay::v2::Peer>(GetArena());
    _impl_.peer_ = reinterpret_cast<::p2p::relay::v2::Peer*>(p);
  }
  return _impl_.peer_;
}
inline ::p2p::relay::v2::Peer* PROTOBUF_NONNULL CircuitRelay::mutable_peer()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::p2p::relay::v2::Peer* _msg = _internal_mutable_peer();
  // @@protoc_insertion_point(field_mutable:p2p.relay.v2.CircuitRelay.peer)
  return _msg;
}
inline void CircuitRelay::set_allocated_peer(::p2p::relay::v2::Peer* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.peer_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.peer_ = reinterpret_cast<::p2p::relay::v2::Peer*>(value);
  // @@protoc_insertion_point(field_set_allocated:p2p.relay.v2.CircuitRelay.peer)
}

// .p2p.relay.v2.Status status = 4;
inline bool CircuitRelay::has_status() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  PROTOBUF_ASSUME(!value || _impl_.status_ != nullptr);
  return value;
}
inline void CircuitRelay::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.status_ != nullptr) _impl_.status_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::p2p::relay::v2::Status& CircuitRelay::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::p2p::relay::v2::Status* p = _impl_.status_;
  return p != nullptr ? *p : reinterpret_cast<const ::p2p::relay::v2::Status&>(::p2p::relay::v2::_Status_default_instance_);
}
inline const ::p2p::relay::v2::Status& CircuitRelay::status() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:p2p.relay.v2.CircuitRelay.status)
  return _internal_status();
}
inline void CircuitRelay::unsafe_arena_set_allocated_status(
    ::p2p::relay::v2::Status* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.status_);
  }
  _impl_.status_ = reinterpret_cast<::p2p::relay::v2::Status*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:p2p.relay.v2.CircuitRelay.status)
}
inline ::p2p::relay::v2::Status* PROTOBUF_NULLABLE CircuitRelay::release_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::p2p::relay::v2::Status* released = _impl_.status_;
  _impl_.status_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::p2p::relay::v2::Status* PROTOBUF_NULLABLE CircuitRelay::unsafe_arena_release_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:p2p.relay.v2.CircuitRelay.status)

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::p2p::relay::v2::Status* temp = _impl_.status_;
  _impl_.status_ = nullptr;
  return temp;
}
inline ::p2p::relay::v2::Status* PROTOBUF_NONNULL CircuitRelay::_internal_mutable_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.status_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::p2p::relay::v2::Status>(GetArena());
    _impl_.status_ = reinterpret_cast<::p2p::relay::v2::Status*>(p);
  }
  return _impl_.status_;
}
inline ::p2p::relay::v2::Status* PROTOBUF_NONNULL CircuitRelay::mutable_status()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::p2p::relay::v2::Status* _msg = _internal_mutable_status();
  // @@protoc_insertion_point(field_mutable:p2p.relay.v2.CircuitRelay.status)
  return _msg;
}
inline void CircuitRelay::set_allocated_status(::p2p::relay::v2::Status* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.status_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }

  _impl_.status_ = reinterpret_cast<::p2p::relay::v2::Status*>(value);
  // @@protoc_insertion_point(field_set_allocated:p2p.relay.v2.CircuitRelay.status)
}

// -------------------------------------------------------------------

// Reservation

// uint64 expire = 1;
inline void Reservation::clear_expire() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.expire_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::uint64_t Reservation::expire() const {
  // @@protoc_insertion_point(field_get:p2p.relay.v2.Reservation.expire)
  return _internal_expire();
}
inline void Reservation::set_expire(::uint64_t value) {
  _internal_set_expire(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:p2p.relay.v2.Reservation.expire)
}
inline ::uint64_t Reservation::_internal_expire() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.expire_;
}
inline void Reservation::_internal_set_expire(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.expire_ = value;
}

// bytes addr = 2;
inline void Reservation::clear_addr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.addr_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& Reservation::addr() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:p2p.relay.v2.Reservation.addr)
  return _internal_addr();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Reservation::set_addr(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.addr_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:p2p.relay.v2.Reservation.addr)
}
inline ::std::string* PROTOBUF_NONNULL Reservation::mutable_addr()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_addr();
  // @@protoc_insertion_point(field_mutable:p2p.relay.v2.Reservation.addr)
  return _s;
}
inline const ::std::string& Reservation::_internal_addr() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.addr_.Get();
}
inline void Reservation::_internal_set_addr(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.addr_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Reservation::_internal_mutable_addr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.addr_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Reservation::release_addr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:p2p.relay.v2.Reservation.addr)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.addr_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.addr_.Set("", GetArena());
  }
  return released;
}
inline void Reservation::set_allocated_addr(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.addr_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.addr_.IsDefault()) {
    _impl_.addr_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:p2p.relay.v2.Reservation.addr)
}

// bytes voucher = 3;
inline void Reservation::clear_voucher() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.voucher_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& Reservation::voucher() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:p2p.relay.v2.Reservation.voucher)
  return _internal_voucher();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Reservation::set_voucher(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.voucher_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:p2p.relay.v2.Reservation.voucher)
}
inline ::std::string* PROTOBUF_NONNULL Reservation::mutable_voucher()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_voucher();
  // @@protoc_insertion_point(field_mutable:p2p.relay.v2.Reservation.voucher)
  return _s;
}
inline const ::std::string& Reservation::_internal_voucher() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.voucher_.Get();
}
inline void Reservation::_internal_set_voucher(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.voucher_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Reservation::_internal_mutable_voucher() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.voucher_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Reservation::release_voucher() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:p2p.relay.v2.Reservation.voucher)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.voucher_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.voucher_.Set("", GetArena());
  }
  return released;
}
inline void Reservation::set_allocated_voucher(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.voucher_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.voucher_.IsDefault()) {
    _impl_.voucher_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:p2p.relay.v2.Reservation.voucher)
}

// uint64 limit_duration = 4;
inline void Reservation::clear_limit_duration() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.limit_duration_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::uint64_t Reservation::limit_duration() const {
  // @@protoc_insertion_point(field_get:p2p.relay.v2.Reservation.limit_duration)
  return _internal_limit_duration();
}
inline void Reservation::set_limit_duration(::uint64_t value) {
  _internal_set_limit_duration(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:p2p.relay.v2.Reservation.limit_duration)
}
inline ::uint64_t Reservation::_internal_limit_duration() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.limit_duration_;
}
inline void Reservation::_internal_set_limit_duration(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.limit_duration_ = value;
}

// uint64 limit_data = 5;
inline void Reservation::clear_limit_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.limit_data_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::uint64_t Reservation::limit_data() const {
  // @@protoc_insertion_point(field_get:p2p.relay.v2.Reservation.limit_data)
  return _internal_limit_data();
}
inline void Reservation::set_limit_data(::uint64_t value) {
  _internal_set_limit_data(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:p2p.relay.v2.Reservation.limit_data)
}
inline ::uint64_t Reservation::_internal_limit_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.limit_data_;
}
inline void Reservation::_internal_set_limit_data(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.limit_data_ = value;
}

// -------------------------------------------------------------------

// Peer

// bytes id = 1;
inline void Peer::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& Peer::id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:p2p.relay.v2.Peer.id)
  return _internal_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Peer::set_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.id_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:p2p.relay.v2.Peer.id)
}
inline ::std::string* PROTOBUF_NONNULL Peer::mutable_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:p2p.relay.v2.Peer.id)
  return _s;
}
inline const ::std::string& Peer::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_.Get();
}
inline void Peer::_internal_set_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Peer::_internal_mutable_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Peer::release_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:p2p.relay.v2.Peer.id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.id_.Set("", GetArena());
  }
  return released;
}
inline void Peer::set_allocated_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.id_.IsDefault()) {
    _impl_.id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:p2p.relay.v2.Peer.id)
}

// repeated bytes addrs = 2;
inline int Peer::_internal_addrs_size() const {
  return _internal_addrs().size();
}
inline int Peer::addrs_size() const {
  return _internal_addrs_size();
}
inline void Peer::clear_addrs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.addrs_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::std::string* PROTOBUF_NONNULL Peer::add_addrs()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_addrs()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add_mutable:p2p.relay.v2.Peer.addrs)
  return _s;
}
inline const ::std::string& Peer::addrs(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:p2p.relay.v2.Peer.addrs)
  return _internal_addrs().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL Peer::mutable_addrs(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:p2p.relay.v2.Peer.addrs)
  return _internal_mutable_addrs()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void Peer::set_addrs(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_addrs()->Mutable(index), ::std::forward<Arg_>(value),
                        args... , ::google::protobuf::internal::BytesTag{});
  // @@protoc_insertion_point(field_set:p2p.relay.v2.Peer.addrs)
}
template <typename Arg_, typename... Args_>
inline void Peer::add_addrs(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_addrs(), ::std::forward<Arg_>(value),
      args... , ::google::protobuf::internal::BytesTag{});
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:p2p.relay.v2.Peer.addrs)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& Peer::addrs()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:p2p.relay.v2.Peer.addrs)
  return _internal_addrs();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
Peer::mutable_addrs() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:p2p.relay.v2.Peer.addrs)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_addrs();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
Peer::_internal_addrs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.addrs_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
Peer::_internal_mutable_addrs() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.addrs_;
}

// -------------------------------------------------------------------

// Status

// .p2p.relay.v2.Status.Code code = 1;
inline void Status::clear_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.code_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::p2p::relay::v2::Status_Code Status::code() const {
  // @@protoc_insertion_point(field_get:p2p.relay.v2.Status.code)
  return _internal_code();
}
inline void Status::set_code(::p2p::relay::v2::Status_Code value) {
  _internal_set_code(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:p2p.relay.v2.Status.code)
}
inline ::p2p::relay::v2::Status_Code Status::_internal_code() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::p2p::relay::v2::Status_Code>(_impl_.code_);
}
inline void Status::_internal_set_code(::p2p::relay::v2::Status_Code value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.code_ = value;
}

// string text = 2;
inline void Status::clear_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.text_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& Status::text() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:p2p.relay.v2.Status.text)
  return _internal_text();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Status::set_text(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.text_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:p2p.relay.v2.Status.text)
}
inline ::std::string* PROTOBUF_NONNULL Status::mutable_text()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_text();
  // @@protoc_insertion_point(field_mutable:p2p.relay.v2.Status.text)
  return _s;
}
inline const ::std::string& Status::_internal_text() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.text_.Get();
}
inline void Status::_internal_set_text(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.text_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Status::_internal_mutable_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.text_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Status::release_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:p2p.relay.v2.Status.text)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.text_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.text_.Set("", GetArena());
  }
  return released;
}
inline void Status::set_allocated_text(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.text_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.text_.IsDefault()) {
    _impl_.text_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:p2p.relay.v2.Status.text)
}

// -------------------------------------------------------------------

// ReservationVoucher

// bytes relay = 1;
inline void ReservationVoucher::clear_relay() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.relay_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& ReservationVoucher::relay() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:p2p.relay.v2.ReservationVoucher.relay)
  return _internal_relay();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ReservationVoucher::set_relay(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.relay_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:p2p.relay.v2.ReservationVoucher.relay)
}
inline ::std::string* PROTOBUF_NONNULL ReservationVoucher::mutable_relay()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_relay();
  // @@protoc_insertion_point(field_mutable:p2p.relay.v2.ReservationVoucher.relay)
  return _s;
}
inline const ::std::string& ReservationVoucher::_internal_relay() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.relay_.Get();
}
inline void ReservationVoucher::_internal_set_relay(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.relay_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ReservationVoucher::_internal_mutable_relay() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.relay_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ReservationVoucher::release_relay() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:p2p.relay.v2.ReservationVoucher.relay)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.relay_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.relay_.Set("", GetArena());
  }
  return released;
}
inline void ReservationVoucher::set_allocated_relay(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.relay_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.relay_.IsDefault()) {
    _impl_.relay_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:p2p.relay.v2.ReservationVoucher.relay)
}

// bytes peer = 2;
inline void ReservationVoucher::clear_peer() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.peer_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& ReservationVoucher::peer() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:p2p.relay.v2.ReservationVoucher.peer)
  return _internal_peer();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ReservationVoucher::set_peer(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.peer_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:p2p.relay.v2.ReservationVoucher.peer)
}
inline ::std::string* PROTOBUF_NONNULL ReservationVoucher::mutable_peer()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_peer();
  // @@protoc_insertion_point(field_mutable:p2p.relay.v2.ReservationVoucher.peer)
  return _s;
}
inline const ::std::string& ReservationVoucher::_internal_peer() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.peer_.Get();
}
inline void ReservationVoucher::_internal_set_peer(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.peer_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ReservationVoucher::_internal_mutable_peer() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.peer_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ReservationVoucher::release_peer() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:p2p.relay.v2.ReservationVoucher.peer)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.peer_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.peer_.Set("", GetArena());
  }
  return released;
}
inline void ReservationVoucher::set_allocated_peer(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.peer_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.peer_.IsDefault()) {
    _impl_.peer_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:p2p.relay.v2.ReservationVoucher.peer)
}

// uint64 expiration = 3;
inline void ReservationVoucher::clear_expiration() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.expiration_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::uint64_t ReservationVoucher::expiration() const {
  // @@protoc_insertion_point(field_get:p2p.relay.v2.ReservationVoucher.expiration)
  return _internal_expiration();
}
inline void ReservationVoucher::set_expiration(::uint64_t value) {
  _internal_set_expiration(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:p2p.relay.v2.ReservationVoucher.expiration)
}
inline ::uint64_t ReservationVoucher::_internal_expiration() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.expiration_;
}
inline void ReservationVoucher::_internal_set_expiration(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.expiration_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v2
}  // namespace relay
}  // namespace p2p


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::p2p::relay::v2::CircuitRelay_Type> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::p2p::relay::v2::CircuitRelay_Type>() {
  return ::p2p::relay::v2::CircuitRelay_Type_descriptor();
}
template <>
struct is_proto_enum<::p2p::relay::v2::Status_Code> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::p2p::relay::v2::Status_Code>() {
  return ::p2p::relay::v2::Status_Code_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // proto_2frelay_5fv2_2eproto_2epb_2eh
