// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/relay_v2.proto
// Protobuf C++ Version: 6.33.4

#include "proto/relay_v2.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace p2p {
namespace relay {
namespace v2 {

inline constexpr Status::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        text_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        code_{static_cast< ::p2p::relay::v2::Status_Code >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR Status::Status(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Status_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct StatusDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StatusDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StatusDefaultTypeInternal() {}
  union {
    Status _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StatusDefaultTypeInternal _Status_default_instance_;

inline constexpr ReservationVoucher::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        relay_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        peer_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        expiration_{::uint64_t{0u}} {}

template <typename>
PROTOBUF_CONSTEXPR ReservationVoucher::ReservationVoucher(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ReservationVoucher_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ReservationVoucherDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReservationVoucherDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReservationVoucherDefaultTypeInternal() {}
  union {
    ReservationVoucher _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReservationVoucherDefaultTypeInternal _ReservationVoucher_default_instance_;

inline constexpr Reservation::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        addr_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        voucher_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        expire_{::uint64_t{0u}},
        limit_duration_{::uint64_t{0u}},
        limit_data_{::uint64_t{0u}} {}

template <typename>
PROTOBUF_CONSTEXPR Reservation::Reservation(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Reservation_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ReservationDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReservationDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReservationDefaultTypeInternal() {}
  union {
    Reservation _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReservationDefaultTypeInternal _Reservation_default_instance_;

inline constexpr Peer::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        addrs_{},
        id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR Peer::Peer(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Peer_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PeerDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PeerDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PeerDefaultTypeInternal() {}
  union {
    Peer _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PeerDefaultTypeInternal _Peer_default_instance_;

inline constexpr CircuitRelay::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        reservation_{nullptr},
        peer_{nullptr},
        status_{nullptr},
        type_{static_cast< ::p2p::relay::v2::CircuitRelay_Type >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR CircuitRelay::CircuitRelay(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CircuitRelay_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CircuitRelayDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CircuitRelayDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CircuitRelayDefaultTypeInternal() {}
  union {
    CircuitRelay _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CircuitRelayDefaultTypeInternal _CircuitRelay_default_instance_;
}  // namespace v2
}  // namespace relay
}  // namespace p2p
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_proto_2frelay_5fv2_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_proto_2frelay_5fv2_2eproto = nullptr;
const ::uint32_t
    TableStruct_proto_2frelay_5fv2_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::p2p::relay::v2::CircuitRelay, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::p2p::relay::v2::CircuitRelay, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::p2p::relay::v2::CircuitRelay, _impl_.reservation_),
        PROTOBUF_FIELD_OFFSET(::p2p::relay::v2::CircuitRelay, _impl_.peer_),
        PROTOBUF_FIELD_OFFSET(::p2p::relay::v2::CircuitRelay, _impl_.status_),
        3,
        0,
        1,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::p2p::relay::v2::Reservation, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::p2p::relay::v2::Reservation, _impl_.expire_),
        PROTOBUF_FIELD_OFFSET(::p2p::relay::v2::Reservation, _impl_.addr_),
        PROTOBUF_FIELD_OFFSET(::p2p::relay::v2::Reservation, _impl_.voucher_),
        PROTOBUF_FIELD_OFFSET(::p2p::relay::v2::Reservation, _impl_.limit_duration_),
        PROTOBUF_FIELD_OFFSET(::p2p::relay::v2::Reservation, _impl_.limit_data_),
        2,
        0,
        1,
        3,
        4,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::p2p::relay::v2::Peer, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::p2p::relay::v2::Peer, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::p2p::relay::v2::Peer, _impl_.addrs_),
        1,
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::p2p::relay::v2::Status, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::p2p::relay::v2::Status, _impl_.code_),
        PROTOBUF_FIELD_OFFSET(::p2p::relay::v2::Status, _impl_.text_),
        1,
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::p2p::relay::v2::ReservationVoucher, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::p2p::relay::v2::ReservationVoucher, _impl_.relay_),
        PROTOBUF_FIELD_OFFSET(::p2p::relay::v2::ReservationVoucher, _impl_.peer_),
        PROTOBUF_FIELD_OFFSET(::p2p::relay::v2::ReservationVoucher, _impl_.expiration_),
        0,
        1,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::p2p::relay::v2::CircuitRelay)},
        {11, sizeof(::p2p::relay::v2::Reservation)},
        {24, sizeof(::p2p::relay::v2::Peer)},
        {31, sizeof(::p2p::relay::v2::Status)},
        {38, sizeof(::p2p::relay::v2::ReservationVoucher)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::p2p::relay::v2::_CircuitRelay_default_instance_._instance,
    &::p2p::relay::v2::_Reservation_default_instance_._instance,
    &::p2p::relay::v2::_Peer_default_instance_._instance,
    &::p2p::relay::v2::_Status_default_instance_._instance,
    &::p2p::relay::v2::_ReservationVoucher_default_instance_._instance,
};
const char descriptor_table_protodef_proto_2frelay_5fv2_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\024proto/relay_v2.proto\022\014p2p.relay.v2\"\343\001\n"
    "\014CircuitRelay\022-\n\004type\030\001 \001(\0162\037.p2p.relay."
    "v2.CircuitRelay.Type\022.\n\013reservation\030\002 \001("
    "\0132\031.p2p.relay.v2.Reservation\022 \n\004peer\030\003 \001"
    "(\0132\022.p2p.relay.v2.Peer\022$\n\006status\030\004 \001(\0132\024"
    ".p2p.relay.v2.Status\",\n\004Type\022\013\n\007RESERVE\020"
    "\000\022\013\n\007CONNECT\020\001\022\n\n\006STATUS\020\002\"h\n\013Reservatio"
    "n\022\016\n\006expire\030\001 \001(\004\022\014\n\004addr\030\002 \001(\014\022\017\n\007vouch"
    "er\030\003 \001(\014\022\026\n\016limit_duration\030\004 \001(\004\022\022\n\nlimi"
    "t_data\030\005 \001(\004\"!\n\004Peer\022\n\n\002id\030\001 \001(\014\022\r\n\005addr"
    "s\030\002 \003(\014\"\367\001\n\006Status\022\'\n\004code\030\001 \001(\0162\031.p2p.r"
    "elay.v2.Status.Code\022\014\n\004text\030\002 \001(\t\"\265\001\n\004Co"
    "de\022\006\n\002OK\020\000\022\027\n\023RESERVATION_REFUSED\020\001\022\033\n\027R"
    "ESOURCE_LIMIT_EXCEEDED\020\002\022\025\n\021PERMISSION_D"
    "ENIED\020\003\022\025\n\021CONNECTION_FAILED\020\004\022\022\n\016NO_RES"
    "ERVATION\020\005\022\025\n\021MALFORMED_MESSAGE\020\006\022\026\n\022UNE"
    "XPECTED_MESSAGE\020\007\"E\n\022ReservationVoucher\022"
    "\r\n\005relay\030\001 \001(\014\022\014\n\004peer\030\002 \001(\014\022\022\n\nexpirati"
    "on\030\003 \001(\004b\006proto3"
};
static ::absl::once_flag descriptor_table_proto_2frelay_5fv2_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_proto_2frelay_5fv2_2eproto = {
    false,
    false,
    736,
    descriptor_table_protodef_proto_2frelay_5fv2_2eproto,
    "proto/relay_v2.proto",
    &descriptor_table_proto_2frelay_5fv2_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_proto_2frelay_5fv2_2eproto::offsets,
    file_level_enum_descriptors_proto_2frelay_5fv2_2eproto,
    file_level_service_descriptors_proto_2frelay_5fv2_2eproto,
};
namespace p2p {
namespace relay {
namespace v2 {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL CircuitRelay_Type_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_proto_2frelay_5fv2_2eproto);
  return file_level_enum_descriptors_proto_2frelay_5fv2_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t CircuitRelay_Type_internal_data_[] = {
    196608u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Status_Code_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_proto_2frelay_5fv2_2eproto);
  return file_level_enum_descriptors_proto_2frelay_5fv2_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t Status_Code_internal_data_[] = {
    524288u, 0u, };
// ===================================================================

class CircuitRelay::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CircuitRelay>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CircuitRelay, _impl_._has_bits_);
};

CircuitRelay::CircuitRelay(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CircuitRelay_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:p2p.relay.v2.CircuitRelay)
}
PROTOBUF_NDEBUG_INLINE CircuitRelay::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::p2p::relay::v2::CircuitRelay& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

CircuitRelay::CircuitRelay(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CircuitRelay& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CircuitRelay_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CircuitRelay* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.reservation_ = (CheckHasBit(cached_has_bits, 0x00000001U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.reservation_)
                : nullptr;
  _impl_.peer_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.peer_)
                : nullptr;
  _impl_.status_ = (CheckHasBit(cached_has_bits, 0x00000004U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.status_)
                : nullptr;
  _impl_.type_ = from._impl_.type_;

  // @@protoc_insertion_point(copy_constructor:p2p.relay.v2.CircuitRelay)
}
PROTOBUF_NDEBUG_INLINE CircuitRelay::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void CircuitRelay::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, reservation_),
           0,
           offsetof(Impl_, type_) -
               offsetof(Impl_, reservation_) +
               sizeof(Impl_::type_));
}
CircuitRelay::~CircuitRelay() {
  // @@protoc_insertion_point(destructor:p2p.relay.v2.CircuitRelay)
  SharedDtor(*this);
}
inline void CircuitRelay::SharedDtor(MessageLite& self) {
  CircuitRelay& this_ = static_cast<CircuitRelay&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.reservation_;
  delete this_._impl_.peer_;
  delete this_._impl_.status_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CircuitRelay::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CircuitRelay(arena);
}
constexpr auto CircuitRelay::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CircuitRelay),
                                            alignof(CircuitRelay));
}
constexpr auto CircuitRelay::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CircuitRelay_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CircuitRelay::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CircuitRelay>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CircuitRelay::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CircuitRelay>(), &CircuitRelay::ByteSizeLong,
              &CircuitRelay::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CircuitRelay, _impl_._cached_size_),
          false,
      },
      &CircuitRelay::kDescriptorMethods,
      &descriptor_table_proto_2frelay_5fv2_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CircuitRelay_class_data_ =
        CircuitRelay::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CircuitRelay::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CircuitRelay_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CircuitRelay_class_data_.tc_table);
  return CircuitRelay_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 3, 0, 2>
CircuitRelay::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CircuitRelay, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    CircuitRelay_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::p2p::relay::v2::CircuitRelay>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .p2p.relay.v2.Status status = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 2, 2,
      PROTOBUF_FIELD_OFFSET(CircuitRelay, _impl_.status_)}},
    // .p2p.relay.v2.CircuitRelay.Type type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CircuitRelay, _impl_.type_), 3>(),
     {8, 3, 0,
      PROTOBUF_FIELD_OFFSET(CircuitRelay, _impl_.type_)}},
    // .p2p.relay.v2.Reservation reservation = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(CircuitRelay, _impl_.reservation_)}},
    // .p2p.relay.v2.Peer peer = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 1, 1,
      PROTOBUF_FIELD_OFFSET(CircuitRelay, _impl_.peer_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .p2p.relay.v2.CircuitRelay.Type type = 1;
    {PROTOBUF_FIELD_OFFSET(CircuitRelay, _impl_.type_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // .p2p.relay.v2.Reservation reservation = 2;
    {PROTOBUF_FIELD_OFFSET(CircuitRelay, _impl_.reservation_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .p2p.relay.v2.Peer peer = 3;
    {PROTOBUF_FIELD_OFFSET(CircuitRelay, _impl_.peer_), _Internal::kHasBitsOffset + 1, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .p2p.relay.v2.Status status = 4;
    {PROTOBUF_FIELD_OFFSET(CircuitRelay, _impl_.status_), _Internal::kHasBitsOffset + 2, 2, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::p2p::relay::v2::Reservation>()},
      {::_pbi::TcParser::GetTable<::p2p::relay::v2::Peer>()},
      {::_pbi::TcParser::GetTable<::p2p::relay::v2::Status>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void CircuitRelay::Clear() {
// @@protoc_insertion_point(message_clear_start:p2p.relay.v2.CircuitRelay)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(_impl_.reservation_ != nullptr);
      _impl_.reservation_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.peer_ != nullptr);
      _impl_.peer_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(_impl_.status_ != nullptr);
      _impl_.status_->Clear();
    }
  }
  _impl_.type_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CircuitRelay::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CircuitRelay& this_ = static_cast<const CircuitRelay&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CircuitRelay::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CircuitRelay& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:p2p.relay.v2.CircuitRelay)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .p2p.relay.v2.CircuitRelay.Type type = 1;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_type() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_type(), target);
    }
  }

  // .p2p.relay.v2.Reservation reservation = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.reservation_, this_._impl_.reservation_->GetCachedSize(), target,
        stream);
  }

  // .p2p.relay.v2.Peer peer = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.peer_, this_._impl_.peer_->GetCachedSize(), target,
        stream);
  }

  // .p2p.relay.v2.Status status = 4;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, *this_._impl_.status_, this_._impl_.status_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:p2p.relay.v2.CircuitRelay)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CircuitRelay::ByteSizeLong(const MessageLite& base) {
  const CircuitRelay& this_ = static_cast<const CircuitRelay&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CircuitRelay::ByteSizeLong() const {
  const CircuitRelay& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:p2p.relay.v2.CircuitRelay)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // .p2p.relay.v2.Reservation reservation = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.reservation_);
    }
    // .p2p.relay.v2.Peer peer = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.peer_);
    }
    // .p2p.relay.v2.Status status = 4;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.status_);
    }
    // .p2p.relay.v2.CircuitRelay.Type type = 1;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_type() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_type());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CircuitRelay::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CircuitRelay*>(&to_msg);
  auto& from = static_cast<const CircuitRelay&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:p2p.relay.v2.CircuitRelay)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(from._impl_.reservation_ != nullptr);
      if (_this->_impl_.reservation_ == nullptr) {
        _this->_impl_.reservation_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.reservation_);
      } else {
        _this->_impl_.reservation_->MergeFrom(*from._impl_.reservation_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.peer_ != nullptr);
      if (_this->_impl_.peer_ == nullptr) {
        _this->_impl_.peer_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.peer_);
      } else {
        _this->_impl_.peer_->MergeFrom(*from._impl_.peer_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(from._impl_.status_ != nullptr);
      if (_this->_impl_.status_ == nullptr) {
        _this->_impl_.status_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.status_);
      } else {
        _this->_impl_.status_->MergeFrom(*from._impl_.status_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_type() != 0) {
        _this->_impl_.type_ = from._impl_.type_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CircuitRelay::CopyFrom(const CircuitRelay& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:p2p.relay.v2.CircuitRelay)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CircuitRelay::InternalSwap(CircuitRelay* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CircuitRelay, _impl_.type_)
      + sizeof(CircuitRelay::_impl_.type_)
      - PROTOBUF_FIELD_OFFSET(CircuitRelay, _impl_.reservation_)>(
          reinterpret_cast<char*>(&_impl_.reservation_),
          reinterpret_cast<char*>(&other->_impl_.reservation_));
}

::google::protobuf::Metadata CircuitRelay::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Reservation::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Reservation>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Reservation, _impl_._has_bits_);
};

Reservation::Reservation(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Reservation_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:p2p.relay.v2.Reservation)
}
PROTOBUF_NDEBUG_INLINE Reservation::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::p2p::relay::v2::Reservation& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        addr_(arena, from.addr_),
        voucher_(arena, from.voucher_) {}

Reservation::Reservation(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Reservation& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Reservation_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Reservation* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, expire_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, expire_),
           offsetof(Impl_, limit_data_) -
               offsetof(Impl_, expire_) +
               sizeof(Impl_::limit_data_));

  // @@protoc_insertion_point(copy_constructor:p2p.relay.v2.Reservation)
}
PROTOBUF_NDEBUG_INLINE Reservation::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        addr_(arena),
        voucher_(arena) {}

inline void Reservation::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, expire_),
           0,
           offsetof(Impl_, limit_data_) -
               offsetof(Impl_, expire_) +
               sizeof(Impl_::limit_data_));
}
Reservation::~Reservation() {
  // @@protoc_insertion_point(destructor:p2p.relay.v2.Reservation)
  SharedDtor(*this);
}
inline void Reservation::SharedDtor(MessageLite& self) {
  Reservation& this_ = static_cast<Reservation&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.addr_.Destroy();
  this_._impl_.voucher_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Reservation::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Reservation(arena);
}
constexpr auto Reservation::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Reservation),
                                            alignof(Reservation));
}
constexpr auto Reservation::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Reservation_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Reservation::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Reservation>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Reservation::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Reservation>(), &Reservation::ByteSizeLong,
              &Reservation::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Reservation, _impl_._cached_size_),
          false,
      },
      &Reservation::kDescriptorMethods,
      &descriptor_table_proto_2frelay_5fv2_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Reservation_class_data_ =
        Reservation::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Reservation::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Reservation_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Reservation_class_data_.tc_table);
  return Reservation_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 0, 2>
Reservation::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Reservation, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Reservation_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::p2p::relay::v2::Reservation>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint64 expire = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Reservation, _impl_.expire_), 2>(),
     {8, 2, 0,
      PROTOBUF_FIELD_OFFSET(Reservation, _impl_.expire_)}},
    // bytes addr = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(Reservation, _impl_.addr_)}},
    // bytes voucher = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 1, 0,
      PROTOBUF_FIELD_OFFSET(Reservation, _impl_.voucher_)}},
    // uint64 limit_duration = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Reservation, _impl_.limit_duration_), 3>(),
     {32, 3, 0,
      PROTOBUF_FIELD_OFFSET(Reservation, _impl_.limit_duration_)}},
    // uint64 limit_data = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Reservation, _impl_.limit_data_), 4>(),
     {40, 4, 0,
      PROTOBUF_FIELD_OFFSET(Reservation, _impl_.limit_data_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 expire = 1;
    {PROTOBUF_FIELD_OFFSET(Reservation, _impl_.expire_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // bytes addr = 2;
    {PROTOBUF_FIELD_OFFSET(Reservation, _impl_.addr_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes voucher = 3;
    {PROTOBUF_FIELD_OFFSET(Reservation, _impl_.voucher_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // uint64 limit_duration = 4;
    {PROTOBUF_FIELD_OFFSET(Reservation, _impl_.limit_duration_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // uint64 limit_data = 5;
    {PROTOBUF_FIELD_OFFSET(Reservation, _impl_.limit_data_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void Reservation::Clear() {
// @@protoc_insertion_point(message_clear_start:p2p.relay.v2.Reservation)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.addr_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.voucher_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000001cU)) {
    ::memset(&_impl_.expire_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.limit_data_) -
        reinterpret_cast<char*>(&_impl_.expire_)) + sizeof(_impl_.limit_data_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Reservation::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Reservation& this_ = static_cast<const Reservation&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Reservation::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Reservation& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:p2p.relay.v2.Reservation)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // uint64 expire = 1;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_expire() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          1, this_._internal_expire(), target);
    }
  }

  // bytes addr = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_addr().empty()) {
      const ::std::string& _s = this_._internal_addr();
      target = stream->WriteBytesMaybeAliased(2, _s, target);
    }
  }

  // bytes voucher = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_voucher().empty()) {
      const ::std::string& _s = this_._internal_voucher();
      target = stream->WriteBytesMaybeAliased(3, _s, target);
    }
  }

  // uint64 limit_duration = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_limit_duration() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          4, this_._internal_limit_duration(), target);
    }
  }

  // uint64 limit_data = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_limit_data() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          5, this_._internal_limit_data(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:p2p.relay.v2.Reservation)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Reservation::ByteSizeLong(const MessageLite& base) {
  const Reservation& this_ = static_cast<const Reservation&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Reservation::ByteSizeLong() const {
  const Reservation& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:p2p.relay.v2.Reservation)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // bytes addr = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_addr().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_addr());
      }
    }
    // bytes voucher = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_voucher().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_voucher());
      }
    }
    // uint64 expire = 1;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_expire() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_expire());
      }
    }
    // uint64 limit_duration = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_limit_duration() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_limit_duration());
      }
    }
    // uint64 limit_data = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_limit_data() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_limit_data());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Reservation::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Reservation*>(&to_msg);
  auto& from = static_cast<const Reservation&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:p2p.relay.v2.Reservation)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_addr().empty()) {
        _this->_internal_set_addr(from._internal_addr());
      } else {
        if (_this->_impl_.addr_.IsDefault()) {
          _this->_internal_set_addr("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_voucher().empty()) {
        _this->_internal_set_voucher(from._internal_voucher());
      } else {
        if (_this->_impl_.voucher_.IsDefault()) {
          _this->_internal_set_voucher("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_expire() != 0) {
        _this->_impl_.expire_ = from._impl_.expire_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_limit_duration() != 0) {
        _this->_impl_.limit_duration_ = from._impl_.limit_duration_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_limit_data() != 0) {
        _this->_impl_.limit_data_ = from._impl_.limit_data_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Reservation::CopyFrom(const Reservation& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:p2p.relay.v2.Reservation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Reservation::InternalSwap(Reservation* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.addr_, &other->_impl_.addr_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.voucher_, &other->_impl_.voucher_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Reservation, _impl_.limit_data_)
      + sizeof(Reservation::_impl_.limit_data_)
      - PROTOBUF_FIELD_OFFSET(Reservation, _impl_.expire_)>(
          reinterpret_cast<char*>(&_impl_.expire_),
          reinterpret_cast<char*>(&other->_impl_.expire_));
}

::google::protobuf::Metadata Reservation::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Peer::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Peer>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Peer, _impl_._has_bits_);
};

Peer::Peer(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Peer_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:p2p.relay.v2.Peer)
}
PROTOBUF_NDEBUG_INLINE Peer::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::p2p::relay::v2::Peer& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        addrs_{visibility, arena, from.addrs_},
        id_(arena, from.id_) {}

Peer::Peer(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Peer& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Peer_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Peer* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:p2p.relay.v2.Peer)
}
PROTOBUF_NDEBUG_INLINE Peer::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        addrs_{visibility, arena},
        id_(arena) {}

inline void Peer::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Peer::~Peer() {
  // @@protoc_insertion_point(destructor:p2p.relay.v2.Peer)
  SharedDtor(*this);
}
inline void Peer::SharedDtor(MessageLite& self) {
  Peer& this_ = static_cast<Peer&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Peer::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Peer(arena);
}
constexpr auto Peer::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Peer, _impl_.addrs_) +
          decltype(Peer::_impl_.addrs_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(Peer), alignof(Peer), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Peer::PlacementNew_,
                                 sizeof(Peer),
                                 alignof(Peer));
  }
}
constexpr auto Peer::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Peer_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Peer::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Peer>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Peer::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Peer>(), &Peer::ByteSizeLong,
              &Peer::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Peer, _impl_._cached_size_),
          false,
      },
      &Peer::kDescriptorMethods,
      &descriptor_table_proto_2frelay_5fv2_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Peer_class_data_ =
        Peer::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Peer::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Peer_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Peer_class_data_.tc_table);
  return Peer_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
Peer::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Peer, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Peer_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::p2p::relay::v2::Peer>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated bytes addrs = 2;
    {::_pbi::TcParser::FastBR1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(Peer, _impl_.addrs_)}},
    // bytes id = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 1, 0,
      PROTOBUF_FIELD_OFFSET(Peer, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes id = 1;
    {PROTOBUF_FIELD_OFFSET(Peer, _impl_.id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // repeated bytes addrs = 2;
    {PROTOBUF_FIELD_OFFSET(Peer, _impl_.addrs_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kBytes | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void Peer::Clear() {
// @@protoc_insertion_point(message_clear_start:p2p.relay.v2.Peer)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.addrs_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.id_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Peer::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Peer& this_ = static_cast<const Peer&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Peer::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Peer& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:p2p.relay.v2.Peer)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bytes id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_id().empty()) {
      const ::std::string& _s = this_._internal_id();
      target = stream->WriteBytesMaybeAliased(1, _s, target);
    }
  }

  // repeated bytes addrs = 2;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (int i = 0, n = this_._internal_addrs_size(); i < n; ++i) {
      const auto& s = this_._internal_addrs().Get(i);
      target = stream->WriteBytes(2, s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:p2p.relay.v2.Peer)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Peer::ByteSizeLong(const MessageLite& base) {
  const Peer& this_ = static_cast<const Peer&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Peer::ByteSizeLong() const {
  const Peer& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:p2p.relay.v2.Peer)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // repeated bytes addrs = 2;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_addrs().size());
      for (int i = 0, n = this_._internal_addrs().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
            this_._internal_addrs().Get(i));
      }
    }
    // bytes id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_id());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Peer::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Peer*>(&to_msg);
  auto& from = static_cast<const Peer&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:p2p.relay.v2.Peer)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_addrs()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_addrs());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_id().empty()) {
        _this->_internal_set_id(from._internal_id());
      } else {
        if (_this->_impl_.id_.IsDefault()) {
          _this->_internal_set_id("");
        }
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Peer::CopyFrom(const Peer& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:p2p.relay.v2.Peer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Peer::InternalSwap(Peer* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.addrs_.InternalSwap(&other->_impl_.addrs_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.id_, &other->_impl_.id_, arena);
}

::google::protobuf::Metadata Peer::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Status::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Status>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Status, _impl_._has_bits_);
};

Status::Status(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Status_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:p2p.relay.v2.Status)
}
PROTOBUF_NDEBUG_INLINE Status::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::p2p::relay::v2::Status& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        text_(arena, from.text_) {}

Status::Status(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Status& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Status_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Status* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.code_ = from._impl_.code_;

  // @@protoc_insertion_point(copy_constructor:p2p.relay.v2.Status)
}
PROTOBUF_NDEBUG_INLINE Status::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        text_(arena) {}

inline void Status::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.code_ = {};
}
Status::~Status() {
  // @@protoc_insertion_point(destructor:p2p.relay.v2.Status)
  SharedDtor(*this);
}
inline void Status::SharedDtor(MessageLite& self) {
  Status& this_ = static_cast<Status&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.text_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Status::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Status(arena);
}
constexpr auto Status::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Status),
                                            alignof(Status));
}
constexpr auto Status::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Status_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Status::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Status>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Status::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Status>(), &Status::ByteSizeLong,
              &Status::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Status, _impl_._cached_size_),
          false,
      },
      &Status::kDescriptorMethods,
      &descriptor_table_proto_2frelay_5fv2_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Status_class_data_ =
        Status::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Status::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Status_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Status_class_data_.tc_table);
  return Status_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 32, 2>
Status::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Status, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Status_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::p2p::relay::v2::Status>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string text = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(Status, _impl_.text_)}},
    // .p2p.relay.v2.Status.Code code = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Status, _impl_.code_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(Status, _impl_.code_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .p2p.relay.v2.Status.Code code = 1;
    {PROTOBUF_FIELD_OFFSET(Status, _impl_.code_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // string text = 2;
    {PROTOBUF_FIELD_OFFSET(Status, _impl_.text_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\23\0\4\0\0\0\0\0"
    "p2p.relay.v2.Status"
    "text"
  }},
};
PROTOBUF_NOINLINE void Status::Clear() {
// @@protoc_insertion_point(message_clear_start:p2p.relay.v2.Status)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.text_.ClearNonDefaultToEmpty();
  }
  _impl_.code_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Status::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Status& this_ = static_cast<const Status&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Status::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Status& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:p2p.relay.v2.Status)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .p2p.relay.v2.Status.Code code = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_code() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_code(), target);
    }
  }

  // string text = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_text().empty()) {
      const ::std::string& _s = this_._internal_text();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "p2p.relay.v2.Status.text");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:p2p.relay.v2.Status)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Status::ByteSizeLong(const MessageLite& base) {
  const Status& this_ = static_cast<const Status&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Status::ByteSizeLong() const {
  const Status& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:p2p.relay.v2.Status)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string text = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_text().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_text());
      }
    }
    // .p2p.relay.v2.Status.Code code = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_code() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_code());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Status::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Status*>(&to_msg);
  auto& from = static_cast<const Status&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:p2p.relay.v2.Status)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_text().empty()) {
        _this->_internal_set_text(from._internal_text());
      } else {
        if (_this->_impl_.text_.IsDefault()) {
          _this->_internal_set_text("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_code() != 0) {
        _this->_impl_.code_ = from._impl_.code_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Status::CopyFrom(const Status& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:p2p.relay.v2.Status)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Status::InternalSwap(Status* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.text_, &other->_impl_.text_, arena);
  swap(_impl_.code_, other->_impl_.code_);
}

::google::protobuf::Metadata Status::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ReservationVoucher::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ReservationVoucher>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ReservationVoucher, _impl_._has_bits_);
};

ReservationVoucher::ReservationVoucher(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ReservationVoucher_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:p2p.relay.v2.ReservationVoucher)
}
PROTOBUF_NDEBUG_INLINE ReservationVoucher::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::p2p::relay::v2::ReservationVoucher& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        relay_(arena, from.relay_),
        peer_(arena, from.peer_) {}

ReservationVoucher::ReservationVoucher(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ReservationVoucher& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ReservationVoucher_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ReservationVoucher* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.expiration_ = from._impl_.expiration_;

  // @@protoc_insertion_point(copy_constructor:p2p.relay.v2.ReservationVoucher)
}
PROTOBUF_NDEBUG_INLINE ReservationVoucher::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        relay_(arena),
        peer_(arena) {}

inline void ReservationVoucher::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.expiration_ = {};
}
ReservationVoucher::~ReservationVoucher() {
  // @@protoc_insertion_point(destructor:p2p.relay.v2.ReservationVoucher)
  SharedDtor(*this);
}
inline void ReservationVoucher::SharedDtor(MessageLite& self) {
  ReservationVoucher& this_ = static_cast<ReservationVoucher&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.relay_.Destroy();
  this_._impl_.peer_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ReservationVoucher::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ReservationVoucher(arena);
}
constexpr auto ReservationVoucher::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ReservationVoucher),
                                            alignof(ReservationVoucher));
}
constexpr auto ReservationVoucher::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ReservationVoucher_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ReservationVoucher::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ReservationVoucher>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ReservationVoucher::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ReservationVoucher>(), &ReservationVoucher::ByteSizeLong,
              &ReservationVoucher::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ReservationVoucher, _impl_._cached_size_),
          false,
      },
      &ReservationVoucher::kDescriptorMethods,
      &descriptor_table_proto_2frelay_5fv2_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ReservationVoucher_class_data_ =
        ReservationVoucher::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ReservationVoucher::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ReservationVoucher_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ReservationVoucher_class_data_.tc_table);
  return ReservationVoucher_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
ReservationVoucher::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ReservationVoucher, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ReservationVoucher_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::p2p::relay::v2::ReservationVoucher>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bytes relay = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(ReservationVoucher, _impl_.relay_)}},
    // bytes peer = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(ReservationVoucher, _impl_.peer_)}},
    // uint64 expiration = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ReservationVoucher, _impl_.expiration_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(ReservationVoucher, _impl_.expiration_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes relay = 1;
    {PROTOBUF_FIELD_OFFSET(ReservationVoucher, _impl_.relay_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes peer = 2;
    {PROTOBUF_FIELD_OFFSET(ReservationVoucher, _impl_.peer_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // uint64 expiration = 3;
    {PROTOBUF_FIELD_OFFSET(ReservationVoucher, _impl_.expiration_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void ReservationVoucher::Clear() {
// @@protoc_insertion_point(message_clear_start:p2p.relay.v2.ReservationVoucher)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.relay_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.peer_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.expiration_ = ::uint64_t{0u};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ReservationVoucher::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ReservationVoucher& this_ = static_cast<const ReservationVoucher&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ReservationVoucher::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ReservationVoucher& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:p2p.relay.v2.ReservationVoucher)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bytes relay = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_relay().empty()) {
      const ::std::string& _s = this_._internal_relay();
      target = stream->WriteBytesMaybeAliased(1, _s, target);
    }
  }

  // bytes peer = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_peer().empty()) {
      const ::std::string& _s = this_._internal_peer();
      target = stream->WriteBytesMaybeAliased(2, _s, target);
    }
  }

  // uint64 expiration = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_expiration() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          3, this_._internal_expiration(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:p2p.relay.v2.ReservationVoucher)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ReservationVoucher::ByteSizeLong(const MessageLite& base) {
  const ReservationVoucher& this_ = static_cast<const ReservationVoucher&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ReservationVoucher::ByteSizeLong() const {
  const ReservationVoucher& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:p2p.relay.v2.ReservationVoucher)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // bytes relay = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_relay().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_relay());
      }
    }
    // bytes peer = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_peer().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_peer());
      }
    }
    // uint64 expiration = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_expiration() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_expiration());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ReservationVoucher::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<ReservationVoucher*>(&to_msg);
  auto& from = static_cast<const ReservationVoucher&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:p2p.relay.v2.ReservationVoucher)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_relay().empty()) {
        _this->_internal_set_relay(from._internal_relay());
      } else {
        if (_this->_impl_.relay_.IsDefault()) {
          _this->_internal_set_relay("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_peer().empty()) {
        _this->_internal_set_peer(from._internal_peer());
      } else {
        if (_this->_impl_.peer_.IsDefault()) {
          _this->_internal_set_peer("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_expiration() != 0) {
        _this->_impl_.expiration_ = from._impl_.expiration_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ReservationVoucher::CopyFrom(const ReservationVoucher& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:p2p.relay.v2.ReservationVoucher)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ReservationVoucher::InternalSwap(ReservationVoucher* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.relay_, &other->_impl_.relay_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.peer_, &other->_impl_.peer_, arena);
  swap(_impl_.expiration_, other->_impl_.expiration_);
}

::google::protobuf::Metadata ReservationVoucher::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v2
}  // namespace relay
}  // namespace p2p
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_proto_2frelay_5fv2_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
