# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.message import Message as _Message

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eidentify.proto\x12\x13libp2p.identify.identify\"\x9d\x01\n\x08Identify\x12\x1f\n\x10protocolVersion\x18\x05 \x01(\tH\x00\x88\x01\x01\x12\x1b\n\x0c\x61gentVersion\x18\x06 \x01(\tH\x01\x88\x01\x01\x12\x1a\n\npublicKey\x18\x01 \x01(\x0cH\x02\x88\x01\x01\x12 \n\x0blistenAddrs\x18\x02 \x03(\x0cH\x03\x88\x01\x01\x12\x1e\n\x0fobservedAddr\x18\x04 \x01(\x0cH\x04\x88\x01\x01\x12\x1c\n\rprotocols\x18\x03 \x03(\tH\x05\x88\x01\x01\x12\x12\n\x03\x65xt\x18\x07 \x01(\x0cH\x06\x88\x01\x01\x42\x0c\n\n_protocolB\x12\n\x10_agentB\x10\n\x12_publicB\x13\n\x15_listenB\x16\n\x18_observedB\x11\n\x13_protocolsB\x07\n\t_ext\"\xa6\x01\n\x12IdentifyExtension\x12\x10\n\x03isp\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x17\n\x08nat_type\x18\x02 \x01(\tH\x01\x88\x01\x01\x12#\n\x0edevice_vendor\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x1b\n\x0cnat_level\x18\x04 \x01(\rH\x03\x88\x01\x01\x12\x17\n\x08is_cgnat\x18\x05 \x01(\x08H\x04\x88\x01\x01\x12#\n\x0eipv6_available\x18\x06 \x01(\x08H\x05\x88\x01\x01\x12\x16\n\x06region\x18\x07 \x01(\tH\x06\x88\x01\x01\x42\x07\n\x05_ispB\n\n\x08_natB\x13\n\x15_deviceB\x0f\n\x11_nat_levelB\x0f\n\x11_is_cgnatB\x17\n\x19_ipv6B\x0b\n\r_regionb\x06proto3')


_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'identify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_IDENTIFY']._serialized_start=34
  _globals['_IDENTIFY']._serialized_end=201
  _globals['_IDENTIFYEXTENSION']._serialized_start=203
  _globals['_IDENTIFYEXTENSION']._serialized_end=363
# @@protoc_insertion_point(module_scope)
