p2p_engine::transport::base::Connection
bytes p2p_engine.transport.base.Connection.read(self, int n=-1)
读取数据 Args: n: 读取字节数，-1 表示读取所有可用数据 Returns: 读取的数据
int p2p_engine.transport.base.Connection.write(self, bytes data)
写入数据 Args: data: 要写入的数据 Returns: 写入的字节数
None p2p_engine.transport.base.Connection.close(self)
关闭连接
Referenced by p2p_engine.transport.webtransport.WebTransportConnection._handle_event, p2p_sdk.client.P2PClient._receive_loop, p2p_engine.transport.webrtc.WebRTCConnection._setup_callbacks, p2p_engine.transport.webrtc.WebRTCConnection._setup_data_channel_callbacks.
bool p2p_engine.transport.base.Connection.is_closed(self)
检查连接是否已关闭
Optional[tuple] p2p_engine.transport.base.Connection.remote_address(self)
获取远程地址
Optional[tuple] p2p_engine.transport.base.Connection.local_address(self)
获取本地地址