p2p_engine::protocol::messages
str p2p_engine::protocol::messages.MULTISTREAM_PROTOCOL_ID
str p2p_engine::protocol::messages.NA_RESPONSE
bytes p2p_engine.protocol.messages.encode_varint(int value)
将无符号整数编码为 varint 格式 Args: value: 要编码的无符号整数 Returns: varint 编码的字节序列 Raises: ValueError: 如果值为负数 Examples: >>> encode_varint(0) b'\\x00' >>> encode_varint(3) b'\\x03' >>> encode_varint(300) b'\\xac\\x02'
Referenced by p2p_engine.protocol.messages.encode_message.
tuple[int, int] p2p_engine.protocol.messages.decode_varint(bytes data, int offset=0)
从 varint 格式解码无符号整数 Args: data: 包含 varint 编码的字节序列 offset: 开始解码的位置偏移量 Returns: (解码后的值, 消耗的字节数) Raises: ValueError: 如果 varint 格式无效或数据不足 Examples: >>> decode_varint(b'\\x00') (0, 1) >>> decode_varint(b'\\xac\\x02') (300, 2)
Referenced by p2p_engine.protocol.messages.decode_message, p2p_engine.protocol.messages.decode_message_with_offset.
bytes p2p_engine.protocol.messages.encode_message(str data)
编码 multistream-select 消息 格式: varint(长度) + UTF-8字符串 + \n Args: data: 要编码的字符串 Returns: 编码后的字节序列 Examples: >>> encode_message("na") b'\\x03na\\n' >>> encode_message("/multistream/1.0.0") b'\\x13/multistream/1.0.0\\n'
References p2p_engine.protocol.messages.encode_varint.
str p2p_engine.protocol.messages.decode_message(bytes data)
解码 multistream-select 消息 Args: data: 要解码的字节序列 Returns: 解码后的字符串 (不含换行符) Raises: ValueError: 如果消息格式无效 Examples: >>> decode_message(b'\\x03na\\n') 'na' >>> decode_message(b'\\x13/multistream/1.0.0\\n') '/multistream/1.0.0'
References p2p_engine.protocol.messages.decode_varint.
tuple[str, int] p2p_engine.protocol.messages.decode_message_with_offset(bytes data, int offset=0)
从指定偏移量解码 multistream-select 消息 Args: data: 要解码的字节序列 offset: 开始解码的位置偏移量 Returns: (解码后的字符串, 消耗的总字节数) Raises: ValueError: 如果消息格式无效
References p2p_engine.protocol.messages.decode_varint.
bool p2p_engine.protocol.messages.is_valid_protocol_id(str protocol_id)
验证协议 ID 是否有效 有效的协议 ID 应该: 1. 以 '/' 开头 2. 不包含空格或控制字符 3. 不为空 Args: protocol_id: 要验证的协议 ID Returns: 是否有效
bool p2p_engine.protocol.messages.is_multistream_protocol(str message)
检查消息是否是 multistream-select 协议 ID Args: message: 要检查的消息字符串 Returns: 是否是 multistream-select 协议 ID
bool p2p_engine.protocol.messages.is_na_response(str message)
检查消息是否是 "na" (不可用) 响应 Args: message: 要检查的消息字符串 Returns: 是否是 "na" 响应