p2p_engine::muxer::mplex
p2p_engine::muxer::mplex.logger
str p2p_engine::muxer::mplex.PROTOCOL_STRING
int p2p_engine::muxer::mplex.INITIAL_CLIENT_STREAM_ID
int p2p_engine::muxer::mplex.INITIAL_SERVER_STREAM_ID
int p2p_engine::muxer::mplex.DEFAULT_BUFFER_SIZE
int p2p_engine::muxer::mplex.MAX_BUFFER_SIZE
int p2p_engine::muxer::mplex.DEFAULT_WINDOW_SIZE
float p2p_engine::muxer::mplex.DEFAULT_ACCEPT_TIMEOUT
int p2p_engine::muxer::mplex.MAX_STREAM_ID
list p2p_engine::muxer::mplex.__all__
str p2p_engine::muxer::mplex.MPLEX_PROTOCOL_ID
None p2p_engine::muxer::mplex.encode_uvarint
tuple[int, int] p2p_engine::muxer::mplex.decode_uvarint
None p2p_engine.muxer.mplex.write_uvarint(bytearray data, int value)
Write a variable-length integer to bytearray. Uses unsigned LEB128 encoding. Args: data: Bytearray to write to value: Integer value to encode
Referenced by p2p_engine.muxer.mplex.MplexFrame.pack.
tuple[int, int] p2p_engine.muxer.mplex.read_uvarint(bytes data, int offset=0)
Read a variable-length integer from bytes. Args: data: Bytes to read from offset: Starting offset Returns: Tuple of (value, bytes_consumed) Raises: MplexProtocolError: If encoding is invalid
Referenced by p2p_engine.muxer.mplex.MplexSession._read_loop, p2p_engine.muxer.mplex.MplexFrame.unpack.