p2p_engine::muxer::mplex_v2
p2p_engine::muxer::mplex_v2.logger
str p2p_engine::muxer::mplex_v2.PROTOCOL_STRING
int p2p_engine::muxer::mplex_v2.INITIAL_CLIENT_STREAM_ID
int p2p_engine::muxer::mplex_v2.INITIAL_SERVER_STREAM_ID
int p2p_engine::muxer::mplex_v2.DEFAULT_BUFFER_SIZE
int p2p_engine::muxer::mplex_v2.MAX_BUFFER_SIZE
int p2p_engine::muxer::mplex_v2.DEFAULT_WINDOW_SIZE
float p2p_engine::muxer::mplex_v2.DEFAULT_ACCEPT_TIMEOUT
int p2p_engine::muxer::mplex_v2.MAX_STREAM_ID
int p2p_engine::muxer::mplex_v2.DEFAULT_MAX_SESSIONS
float p2p_engine::muxer::mplex_v2.SESSION_IDLE_TIMEOUT
list p2p_engine::muxer::mplex_v2.__all__
str p2p_engine::muxer::mplex_v2.MPLEX_PROTOCOL_ID
None p2p_engine::muxer::mplex_v2.encode_uvarint
tuple[int, int] p2p_engine::muxer::mplex_v2.decode_uvarint
None p2p_engine.muxer.mplex_v2.write_uvarint(bytearray data, int value)
Write a variable-length integer to bytearray. Uses unsigned LEB128 encoding. Args: data: Bytearray to write to value: Integer value to encode
Referenced by p2p_engine.muxer.mplex_v2.MplexFrame.pack.
tuple[int, int] p2p_engine.muxer.mplex_v2.read_uvarint(bytes data, int offset=0)
Read a variable-length integer from bytes. Args: data: Bytes to read from offset: Starting offset Returns: Tuple of (value, bytes_consumed) Raises: MplexProtocolError: If encoding is invalid
Referenced by p2p_engine.muxer.mplex_v2.MplexSession._read_loop, p2p_engine.muxer.mplex_v2.MplexFrame.unpack.