p2p_engine::detection::autonat
p2p_engine::detection::autonat.logger
str p2p_engine::detection::autonat.PROTOCOL_ID
float p2p_engine::detection::autonat.DIAL_TIMEOUT
int p2p_engine::detection::autonat.MAX_DIAL_ATTEMPTS
list p2p_engine::detection::autonat.__all__
Optional[tuple] p2p_engine.detection.autonat.parse_multiaddr(bytes data)
Parse multiaddr and extract (ip, port) if applicable. Supports /ip4/<ip>/tcp/<port> and /ip4/<ip>/udp/<port> formats.
bool p2p_engine.detection.autonat.validate_ip_match(str observed_ip, str dial_ip)
Validate that dial-back IP matches observed IP (DDoS protection). Per RFC 3489 Section 12.1.1: Implementations MUST NOT dial any multiaddress unless it is based on the IP address the requesting node is observed as.
bytes p2p_engine.detection.autonat.encode_uvarint(int value)
Encode unsigned varint
Referenced by p2p_engine.detection.autonat.encode_dial_message, p2p_engine.detection.autonat.encode_dial_peer_info, p2p_engine.detection.autonat.encode_dial_response, p2p_engine.detection.autonat.encode_message, p2p_engine.detection.autonat.encode_string.
tuple[int, int] p2p_engine.detection.autonat.decode_uvarint(bytes data, int offset=0)
Decode unsigned varint, returns (value, new_offset)
Referenced by p2p_engine.detection.autonat.decode_dial_peer_info, p2p_engine.detection.autonat.decode_message, p2p_engine.detection.autonat.decode_string.
bytes p2p_engine.detection.autonat.encode_string(str s)
Encode string with length prefix
References p2p_engine.detection.autonat.encode_uvarint.
Referenced by p2p_engine.detection.autonat.encode_dial_response.
tuple[str, int] p2p_engine.detection.autonat.decode_string(bytes data, int offset=0)
Decode string with length prefix, returns (string, new_offset)
References p2p_engine.detection.autonat.decode_uvarint.
bytes p2p_engine.detection.autonat.encode_dial_peer_info(DialPeerInfo peer_info)
Encode DialPeerInfo
References p2p_engine.detection.autonat.encode_uvarint.
Referenced by p2p_engine.detection.autonat.encode_dial_message.
tuple[DialPeerInfo, int] p2p_engine.detection.autonat.decode_dial_peer_info(bytes data, int offset=0)
Decode DialPeerInfo, returns (peer_info, new_offset)
References p2p_engine.detection.autonat.decode_uvarint.
Referenced by p2p_engine.detection.autonat.decode_message.
bytes p2p_engine.detection.autonat.encode_dial_message(DialMessage dial)
Encode Dial message
References p2p_engine.detection.autonat.encode_dial_peer_info, p2p_engine.detection.autonat.encode_uvarint.
Referenced by p2p_engine.detection.autonat.encode_message.
bytes p2p_engine.detection.autonat.encode_dial_response(DialResponse response)
Encode DialResponse message
References p2p_engine.detection.autonat.encode_string, p2p_engine.detection.autonat.encode_uvarint.
Referenced by p2p_engine.detection.autonat.encode_message.
bytes p2p_engine.detection.autonat.encode_message(AutoNATMessage msg)
Encode complete AutoNAT message
References p2p_engine.detection.autonat.encode_dial_message, p2p_engine.detection.autonat.encode_dial_response, p2p_engine.detection.autonat.encode_uvarint.
Referenced by p2p_engine.detection.autonat.AutoNATClient.check_reachability.
tuple[Optional[AutoNATMessage], int] p2p_engine.detection.autonat.decode_message(bytes data, int offset=0)
Decode AutoNAT message, returns (message, new_offset) or (None, offset) on error
References p2p_engine.detection.autonat.decode_dial_peer_info, p2p_engine.detection.autonat.decode_uvarint.
bool p2p_engine.detection.autonat.create_dial_socket(str ip, int port, str protocol)
Default dial function for AutoNAT server. Attempts to create a socket connection to the given address.
str p2p_engine.detection.autonat.get_observed_ip_from_socket(socket.socket sock)
Extract observed IP from a connected socket. Useful for getting the observed IP when handling AutoNAT requests.