p2p_engine::protocol::dcutr::example
p2p_engine::protocol::dcutr::example.level
p2p_engine::protocol::dcutr::example.format
p2p_engine::protocol::dcutr::example.logger
p2p_engine.protocol.dcutr.example.example_dcutr_active_side()
Example: Active side (initiator) of DCUtR upgrade This is the peer that initiates the upgrade from relay to direct.
Referenced by p2p_engine.protocol.dcutr.example.main.
p2p_engine.protocol.dcutr.example.example_dcutr_passive_side()
Example: Passive side (receiver) of DCUtR upgrade This is the peer that receives the upgrade request.
Referenced by p2p_engine.protocol.dcutr.example.main.
p2p_engine.protocol.dcutr.example.example_message_encoding()
Example: Encoding and decoding DCUtR messages
Referenced by p2p_engine.protocol.dcutr.example.main.
p2p_engine.protocol.dcutr.example.example_protocol_flow()
Example: Complete DCUtR protocol flow
Referenced by p2p_engine.protocol.dcutr.example.main.
p2p_engine.protocol.dcutr.example.main()
Run all examples
References p2p_engine.protocol.dcutr.example.example_dcutr_active_side, p2p_engine.protocol.dcutr.example.example_dcutr_passive_side, p2p_engine.protocol.dcutr.example.example_message_encoding, p2p_engine.protocol.dcutr.example.example_protocol_flow, p2p_engine.protocol.dcutr.example.main.
Referenced by p2p_engine.protocol.dcutr.example.main.