src::relay
src::relay.level
src::relay.format
src::relay.logger
src::relay.DEFAULT_RELAY_HOST
src::relay.DEFAULT_RELAY_PORT
src::relay.RELAY_PUBLIC_IP
src::relay.parse
src::relay.serialize
src::relay.get_attribute
Optional[StunMessage] src.relay.parse_stun_message(bytes data)
Parse STUN message from bytes.
bytes src.relay.create_error_response(bytes transaction_id, ErrorCode error_code, str message)
Create STUN error response.
References src.relay._serialize_stun_message.
Referenced by src.relay.RelayServer._handle_allocate, src.relay.RelayServer._handle_control_message, src.relay.RelayServer._handle_create_permission, src.relay.RelayServer._handle_refresh.
bytes src.relay._serialize_stun_message(StunMessage msg)
Serialize STUN message to bytes.
Referenced by src.relay.RelayServer._create_binding_response, src.relay.RelayServer._handle_allocate, src.relay.RelayServer._handle_create_permission, src.relay.RelayServer._handle_refresh, src.relay.create_error_response.
src.relay.main()
Main entry point.
References src.relay.main.
Referenced by src.relay.main.