p2p_engine::dht::routing
p2p_engine::dht::routing.logger
int p2p_engine::dht::routing.ALPHA
int p2p_engine::dht::routing.K
int p2p_engine::dht::routing.BIT_COUNT
int p2p_engine::dht::routing.BYTE_COUNT
bytes p2p_engine.dht.routing.calculate_peer_id(bytes public_key)
Calculate peer ID from public key using SHA-256. Args: public_key: Peer's public key bytes Returns: 32-byte peer ID
int p2p_engine.dht.routing.calculate_distance(bytes id1, bytes id2)
Calculate XOR distance between two peer IDs. The XOR distance is defined as the integer value of the XOR of two IDs. Lower distance means closer in the DHT. Args: id1: First peer ID (32 bytes) id2: Second peer ID (32 bytes) Returns: Integer distance value Raises: ValueError: If IDs are not 32 bytes
Referenced by p2p_engine.dht.routing.RoutingTable.find_closest_peers, p2p_engine.dht.routing.KBucket.get_closest_peers, p2p_engine.dht.routing.KBucket.get_furthest_peers.
int p2p_engine.dht.routing.common_prefix_length(bytes id1, bytes id2)
Calculate the number of leading bits that are identical. Used to determine which k-bucket a peer belongs to. Args: id1: First peer ID (32 bytes) id2: Second peer ID (32 bytes) Returns: Number of leading identical bits (0-256)
Referenced by p2p_engine.dht.routing.RoutingTable._find_bucket.