p2p_engine::muxer::benchmark
p2p_engine::muxer::benchmark.logger
None p2p_engine.muxer.benchmark.run_yamux_benchmarks()
Run benchmarks for yamux implementation.
Referenced by p2p_engine.muxer.benchmark.main.
None p2p_engine.muxer.benchmark.run_mplex_benchmarks()
Run benchmarks for mplex implementation.
Referenced by p2p_engine.muxer.benchmark.main.
p2p_engine.muxer.benchmark.main()
Run all muxer benchmarks.
References p2p_engine.muxer.benchmark.main, p2p_engine.muxer.benchmark.run_mplex_benchmarks, p2p_engine.muxer.benchmark.run_yamux_benchmarks.
Referenced by p2p_engine.muxer.benchmark.main.