p2p_engine::protocol::noise_pb2
None p2p_engine.protocol.noise_pb2._encode_field(bytearray buf, int field_num, bytes value)
Encode a length-delimited field.
References p2p_engine.protocol.noise_pb2._encode_varint.
Referenced by p2p_engine.protocol.noise_pb2.NoiseHandshakePayload.SerializeToString.
None p2p_engine.protocol.noise_pb2._encode_varint(bytearray buf, int value)
Encode a varint.
Referenced by p2p_engine.protocol.noise_pb2._encode_field.
tuple[int, int] p2p_engine.protocol.noise_pb2._decode_varint(bytes data, int pos)
Decode a varint, returns (value, new_pos).
Referenced by p2p_engine.protocol.noise_pb2.NoiseHandshakePayload.ParseFromString.