p2p_engine::dht::provider
p2p_engine::dht::provider.logger
float p2p_engine::dht::provider.PROVIDER_EXPIRATION
int p2p_engine::dht::provider.MAX_PROVIDERS_PER_KEY
bytes p2p_engine.dht.provider.compute_key(bytes key)
Compute the DHT key for content. Uses SHA-256 hash of the input key. Args: key: Input key (can be CID bytes or any content identifier) Returns: 32-byte DHT key
Referenced by p2p_engine.dht.provider.ProviderManager.add_provider, p2p_engine.dht.provider.ProviderManager.get_providers, p2p_engine.dht.provider.ProviderManager.remove_provider.
bytes p2p_engine.dht.provider.create_provider_message(bytes key, bytes peer_id)
Create a provider announcement message. Args: key: Content key being provided peer_id: ID of the provider peer Returns: Encoded message bytes
tuple[bytes, bytes] p2p_engine.dht.provider.parse_provider_message(bytes data)
Parse a provider announcement message. Args: data: Encoded message bytes Returns: Tuple of (key, peer_id) Raises: ValueError: If message is invalid